import SHOWROOM_ROUTES from "./routes";

export type ShowroomParamsList = {
  [SHOWROOM_ROUTES.MAIN]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.COLOR]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.TYPOGRAPHY]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.ICONS]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.PICTOGRAMS]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.LOGOS]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.BUTTONS]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.SELECTION]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.ADVICE]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.ACCORDION]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.TEXT_FIELDS]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.TOASTS]: undefined;
  [SHOWROOM_ROUTES.LEGACY.PICTOGRAMS]: undefined;
  [SHOWROOM_ROUTES.LEGACY.ILLUSTRATIONS]: undefined;
};
