import SHOWROOM_ROUTES from "./routes";

export type ShowroomParamsList = {
  [SHOWROOM_ROUTES.MAIN]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.COLOR.id]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.TYPOGRAPHY.id]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.ICONS.id]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.PICTOGRAMS.id]: undefined;
  [SHOWROOM_ROUTES.FOUNDATION.LOGOS.id]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.BUTTONS.id]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.SELECTION.id]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.ADVICE.id]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.ACCORDION.id]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.TEXT_FIELDS.id]: undefined;
  [SHOWROOM_ROUTES.COMPONENTS.TOASTS.id]: undefined;
  [SHOWROOM_ROUTES.LEGACY.PICTOGRAMS.id]: undefined;
  [SHOWROOM_ROUTES.LEGACY.ILLUSTRATIONS.id]: undefined;
};
