const SHOWROOM_ROUTES = {
  MAIN: "SHOWROOM_MAIN",
  FOUNDATION: {
    COLOR: "SHOWROOM_COLOR",
    TYPOGRAPHY: "SHOWROOM_TYPOGRAPHY",
    ICONS: "SHOWROOM_ICONS",
    PICTOGRAMS: "SHOWROOM_PICTOGRAMS",
    LOGOS: "SHOWROOM_LOGOS"
  },
  COMPONENTS: {
    BUTTONS: "SHOWROOM_BUTTONS",
    TEXT_FIELDS: "SHOWROOM_TEXT_FIELDS",
    TOASTS: "SHOWROOM_TOASTS"
  },
  LEGACY: {
    PICTOGRAMS: "SHOWROOM_LEGACY_PICTOGRAMS",
    ILLUSTRATIONS: "SHOWROOM_LEGACY_ILLUSTRATIONS"
  } as const
} as const;

export default SHOWROOM_ROUTES;
