export const PaymentsNoticeRoutes = {
  PAYMENT_NOTICE_NAVIGATOR: "PAYMENT_NOTICE_NAVIGATOR",
  PAYMENT_NOTICE_DETAILS: "PAYMENT_NOTICE_DETAILS",
  PAYMENT_NOTICE_CART_ITEM_DETAILS: "PAYMENT_NOTICE_CART_ITEM_DETAILS",
  PAYMENT_NOTICE_LIST_SCREEN: "PAYMENT_NOTICE_LIST_SCREEN",
  PAYMENT_NOTICE_PREVIEW_SCREEN: "PAYMENT_NOTICE_PREVIEW_SCREEN",
  PAYMENT_NOTICE_LOADING_SCREEN: "PAYMENT_NOTICE_LOADING_SCREEN"
} as const;
