import { PersistPartial } from "redux-persist";
import { VersionInfoState } from "../../common/versionInfo/store/reducers/versionInfo";

import { PersistedAuthenticationState } from "../../features/authentication/common/store/reducers";
import { CieState } from "../../features/authentication/login/cie/store/reducers/cie";
import { BonusState } from "../../features/bonus/common/store/reducers";
import { PersistedFeaturesState } from "../../features/common/store/reducers";
import { PersistedIdentificationState } from "../../features/identification/store/reducers";
import { PersistedLollipopState } from "../../features/lollipop/store";
import { EmailValidationState } from "../../features/mailCheck/store/reducers/emailValidation";
import { OnboardingState } from "../../features/onboarding/store/reducers";
import { PersistedNotificationsState } from "../../features/pushNotifications/store/reducers";
import { ProfileState } from "../../features/settings/common/store/reducers";
import { UserDataProcessingState } from "../../features/settings/common/store/reducers/userDataProcessing";
import { TrialSystemState } from "../../features/trialSystem/store/reducers";
import { AppState } from "./appState";
import { AssistanceToolsState } from "./assistanceTools";
import { BackedInfoState } from "./backendStatus/backendInfo";
import { RemoteConfigState } from "./backendStatus/remoteConfig";
import { SectionStatusState } from "./backendStatus/sectionStatus";
import { StatusMessagesState } from "./backendStatus/statusMessages";
import { ContentState } from "./content";
import { CrossSessionsState } from "./crossSessions";
import { PersistedDebugState } from "./debug";
import { PersistedEntitiesState } from "./entities";
import { InstallationState } from "./installation";
import { NavigationState } from "./navigation";
import { PersistedPreferencesState } from "./persistedPreferences";
import { PreferencesState } from "./preferences";
import { SearchState } from "./search";
import { StartupState } from "./startup";

export type GlobalState = Readonly<{
  appState: AppState;
  navigation: NavigationState;
  authentication: PersistedAuthenticationState;
  remoteConfig: RemoteConfigState;
  statusMessages: StatusMessagesState;
  sectionStatus: SectionStatusState;
  backendInfo: BackedInfoState;
  versionInfo: VersionInfoState;
  entities: PersistedEntitiesState;
  notifications: PersistedNotificationsState;
  onboarding: OnboardingState;
  profile: ProfileState;
  userDataProcessing: UserDataProcessingState;
  preferences: PreferencesState;
  persistedPreferences: PersistedPreferencesState;
  content: ContentState;
  identification: PersistedIdentificationState;
  installation: InstallationState;
  debug: PersistedDebugState;
  search: SearchState;
  emailValidation: EmailValidationState;
  cie: CieState;
  bonus: BonusState;
  features: PersistedFeaturesState;
  crossSessions: CrossSessionsState;
  assistanceTools: AssistanceToolsState;
  startup: StartupState;
  lollipop: PersistedLollipopState;
  trialSystem: TrialSystemState;
}>;

export type PersistedGlobalState = GlobalState & PersistPartial;
