const ROUTES = {
  // Ingress
  INGRESS: "INGRESS",

  // UNSUPPORTED_DEVICE
  UNSUPPORTED_DEVICE: "UNSUPPORTED_DEVICE",
  // Markdown
  MARKDOWN: "MARKDOWN",

  // Mail verification
  CHECK_EMAIL: "CHECK_EMAIL",
  CHECK_EMAIL_NOT_VERIFIED: "CHECK_EMAIL_NOT_VERIFIED",
  CHECK_EMAIL_ALREADY_TAKEN: "CHECK_EMAIL_ALREADY_TAKEN",

  // Onboarding
  ONBOARDING: "ONBOARDING",
  ONBOARDING_TOS: "ONBOARDING_TOS",
  ONBOARDING_SHARE_DATA: "ONBOARDING_SHARE_DATA",
  ONBOARDING_SERVICES_PREFERENCE: "ONBOARDING_SERVICES_PREFERENCE",
  ONBOARDING_SERVICES_PREFERENCE_COMPLETE:
    "ONBOARDING_SERVICES_PREFERENCE_COMPLETE",
  ONBOARDING_PIN: "ONBOARDING_PIN",
  ONBOARDING_MISSING_DEVICE_PIN: "ONBOARDING_MISSING_DEVICE_PIN",
  ONBOARDING_MISSING_DEVICE_BIOMETRIC: "ONBOARDING_MISSING_DEVICE_BIOMETRIC",
  ONBOARDING_FINGERPRINT: "ONBOARDING_FINGERPRINT",
  ONBOARDING_COMPLETED: "ONBOARDING_COMPLETED",
  ONBOARDING_NOTIFICATIONS_PREFERENCES: "ONBOARDING_NOTIFICATIONS_PREFERENCES",
  ONBOARDING_NOTIFICATIONS_INFO_SCREEN_CONSENT:
    "ONBOARDING_NOTIFICATIONS_INFO_SCREEN_CONSENT",
  ONBOARDING_INSERT_EMAIL_SCREEN: "ONBOARDING_INSERT_EMAIL_SCREEN",
  ONBOARDING_EMAIL_VERIFICATION_SCREEN: "ONBOARDING_EMAIL_VERIFICATION_SCREEN",

  // Wallet
  WALLET_HOME: "WALLET_HOME",

  // Payments
  PAYMENTS_HOME: "PAYMENTS_HOME",

  // Main
  MAIN: "MAIN",

  // Barcode scan
  BARCODE_SCAN_TAB_EMPTY: "BARCODE_SCAN_TAB_EMPTY",
  BARCODE_SCAN: "BARCODE_SCAN",

  // Used when the App is in background
  BACKGROUND: "BACKGROUND",

  // No internet connection or missing session
  OFFLINE_FAILURE: "OFFLINE_FAILURE",

  WORKUNIT_GENERIC_FAILURE: "WORKUNIT_GENERIC_FAILURE",
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND"
} as const;

export default ROUTES;
