const ROUTES = {
  // Ingress
  INGRESS: "INGRESS",

  // Authentication
  AUTHENTICATION: "AUTHENTICATION",
  AUTHENTICATION_LANDING: "AUTHENTICATION_LANDING",
  AUTHENTICATION_IDP_SELECTION: "AUTHENTICATION_IPD_SELECTION",
  AUTHENTICATION_IDP_LOGIN: "AUTHENTICATION_IPD_LOGIN",
  AUTHENTICATION_LOGIN: "AUTHENTICATION_LOGIN",
  AUTHENTICATION_SPID_INFORMATION_REQUEST:
    "AUTHENTICATION_SPID_INFORMATION_REQUEST",

  // Onboarding
  ONBOARDING: "ONBOARDING",
  ONBOARDING_TOS: "ONBOARDING_TOS",
  ONBOARDING_PIN: "ONBOARDING_PIN",

  // Main
  MAIN: "MAIN",
  MAIN_MESSAGES: "MAIN_MESSAGES",
  MAIN_PROFILE: "MAIN_PROFILE",

  //Portfolio
  PORTFOLIO_ACQUIRE_QRCODE: "PORTFOLIO_ACQUIRE_QRCODE",
  PORTFOLIO_INSERT_QRCODE_DATA: "PORTFOLIO_INSERT_QRCODE_DATA",
  PORTFOLIO_PAYMENT_SUMMARY: "PORTFOLIO_PAYMENT_SUMMARY",

};

export default ROUTES;
