export const PaymentsTransactionRoutes = {
  PAYMENT_TRANSACTION_NAVIGATOR: "PAYMENT_TRANSACTION_NAVIGATOR",
  PAYMENT_TRANSACTION_DETAILS: "PAYMENT_TRANSACTION_DETAILS",
  PAYMENT_TRANSACTION_OPERATION_DETAILS: "PAYMENT_TRANSACTION_OPERATION_DETAILS"
} as const;
