export const PaymentsTransactionRoutes = {
  PAYMENTS_TRANSACTION_NAVIGATOR: "PAYMENTS_TRANSACTION_NAVIGATOR",
  PAYMENTS_TRANSACTION_DETAILS: "PAYMENTS_TRANSACTION_DETAILS",
  PAYMENTS_TRANSACTION_OPERATION_DETAILS:
    "PAYMENTS_TRANSACTION_OPERATION_DETAILS"
} as const;
