export const PaymentsTransactionRoutes = {
  PAYMENT_TRANSACTION_NAVIGATOR: "PAYMENT_TRANSACTION_NAVIGATOR",
  PAYMENT_TRANSACTION_DETAILS: "PAYMENT_TRANSACTION_DETAILS",
  PAYMENT_TRANSACTION_OPERATION_DETAILS:
    "PAYMENT_TRANSACTION_OPERATION_DETAILS",
  PAYMENT_TRANSACTION_LIST: "PAYMENT_TRANSACTION_LIST"
} as const;
