export const IDPayCodeRoutes = {
  IDPAY_CODE_MAIN: "IDPAY_CODE_MAIN",
  IDPAY_CODE_LANDING: "IDPAY_CODE_LANDING",
  IDPAY_CODE_DISPLAY: "IDPAY_CODE_DISPLAY",
  IDPAY_CODE_RESULT: "IDPAY_CODE_RESULT"
} as const;
