export const IdPayCodeRoutes = {
  IDPAY_CODE_MAIN: "IDPAY_CODE_MAIN",
  IDPAY_CODE_ONBOARDING: "IDPAY_CODE_ONBOARDING",
  IDPAY_CODE_DISPLAY: "IDPAY_CODE_DISPLAY",
  IDPAY_CODE_RENEW: "IDPAY_CODE_RENEW",
  IDPAY_CODE_RESULT: "IDPAY_CODE_RESULT"
} as const;
