/* eslint-disable functional/immutable-data */
/**
 * Main app entrypoint
 */
// Shim file generated by rn-nodeify
import "./shim";
import "react-native-get-random-values";
import "react-native-quick-base64";
import {
  AlertStatic as Alert,
  AppRegistry,
  Text,
  TextInput,
  LogBox
} from "react-native";
import DeviceInfo from "react-native-device-info";
import {
  setJSExceptionHandler,
  setNativeExceptionHandler
} from "react-native-exception-handler";
import * as Sentry from "@sentry/react-native";

import App from "./ts/App";
import { initI18n } from "./ts/i18n";
import { isMixpanelInstanceInitialized, mixpanelTrack } from "./ts/mixpanel";
import { name as appName } from "./app.json";

void initI18n();

const errorHandler = (e, isFatal) => {
  if (isFatal) {
    Sentry.captureMessage("JSException");
    Sentry.captureException(e);
    if (isMixpanelInstanceInitialized()) {
      mixpanelTrack("APPLICATION_ERROR", {
        TYPE: "js",
        ERROR: JSON.stringify(e),
        APP_VERSION: DeviceInfo.getReadableVersion()
      });
    }
    Alert.alert(
      "Unexpected error occurred",
      `
        Error: ${isFatal ? "Fatal:" : ""} ${e.name} ${e.message}
        You will need to restart the app.
        `
    );
  } else {
    // eslint-disable-next-line no-console
    console.log(e); // So that we can see it in the ADB logs in case of Android if needed
  }
};

setJSExceptionHandler(errorHandler);
setNativeExceptionHandler(exceptionString => {
  Sentry.captureMessage("NativeException");
  Sentry.captureException(exceptionString);
  if (isMixpanelInstanceInitialized()) {
    mixpanelTrack("APPLICATION_ERROR", {
      TYPE: "native",
      ERROR: exceptionString,
      APP_VERSION: DeviceInfo.getReadableVersion()
    });
  }
});

AppRegistry.registerComponent(appName, () => App);
