/**
 * All the actions related constants.
 */

// Application
export const APPLICATION_INITIALIZED: "APPLICATION_INITIALIZED" =
  "APPLICATION_INITIALIZED";
export const APP_STATE_CHANGE_ACTION: "APP_STATE_CHANGE_ACTION" =
  "APP_STATE_CHANGE_ACTION";

// Navigation
export const NAVIGATION_RESTORE: "NAVIGATION_RESTORE" = "NAVIGATION_RESTORE";

// Authentication
export const START_AUTHENTICATION: "START_AUTHENTICATION" =
  "START_AUTHENTICATION";
export const IDP_SELECTED: "IDP_SELECTED" = "IDP_SELECTED";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILURE: "LOGIN_FAILURE" = "LOGIN_FAILURE";
export const LOGOUT: "LOGOUT" = "LOGOUT";
export const SESSION_LOAD_REQUEST: "SESSION_LOAD_REQUEST" =
  "SESSION_LOAD_REQUEST";
export const SESSION_LOAD_SUCCESS: "SESSION_LOAD_SUCCESS" =
  "SESSION_LOAD_SUCCESS";
export const SESSION_LOAD_FAILURE: "SESSION_LOAD_FAILURE" =
  "SESSION_LOAD_FAILURE";
export const AUTHENTICATION_COMPLETED: "AUTHENTICATION_COMPLETED" =
  "AUTHENTICATION_COMPLETED";
export const SESSION_EXPIRED: "SESSION_EXPIRED" = "SESSION_EXPIRED";

// Onboarding
export const START_ONBOARDING: "START_ONBOARDING" = "START_ONBOARDING";
export const ONBOARDING_CHECK_TOS: "ONBOARDING_CHECK_TOS" =
  "ONBOARDING_CHECK_TOS";
export const ONBOARDING_CHECK_PIN: "ONBOARDING_CHECK_PIN" =
  "ONBOARDING_CHECK_PIN";
export const ONBOARDING_CHECK_COMPLETE: "ONBOARDING_CHECK_COMPLETE" =
  "ONBOARDING_CHECK_COMPLETE";
export const TOS_ACCEPT_REQUEST: "TOS_ACCEPT_REQUEST" = "TOS_ACCEPT_REQUEST";
export const TOS_ACCEPT_SUCCESS: "TOS_ACCEPT_SUCCESS" = "TOS_ACCEPT_SUCCESS";
export const PIN_CREATE_REQUEST: "PIN_CREATE_REQUEST" = "PIN_CREATE_REQUEST";
export const PIN_CREATE_SUCCESS: "PIN_CREATE_SUCCESS" = "PIN_CREATE_SUCCESS";
export const PIN_CREATE_FAILURE: "PIN_CREATE_FAILURE" = "PIN_CREATE_FAILURE";

// Notifications
export const NOTIFICATIONS_INSTALLATION_TOKEN_UPDATE: "NOTIFICATIONS_INSTALLATION_TOKEN_UPDATE" =
  "NOTIFICATIONS_INSTALLATION_TOKEN_UPDATE";
export const START_NOTIFICATION_INSTALLATION_UPDATE: "START_NOTIFICATION_INSTALLATION_UPDATE" =
  "START_NOTIFICATION_INSTALLATION_UPDATE";
export const NOTIFICATIONS_INSTALLATION_UPDATE_FAILURE: "NOTIFICATIONS_INSTALLATION_UPDATE_FAILURE" =
  "NOTIFICATIONS_INSTALLATION_UPDATE_FAILURE";

// Pinlogin
export const PIN_LOGIN_INITIALIZE: "PIN_LOGIN_INITIALIZE" =
  "PIN_LOGIN_INITIALIZE";
export const PIN_LOGIN_VALIDATE_REQUEST: "PIN_LOGIN_VALIDATE_REQUEST" =
  "PIN_LOGIN_VALIDATE_REQUEST";
export const PIN_LOGIN_VALIDATE_SUCCESS: "PIN_LOGIN_VALIDATE_SUCCESS" =
  "PIN_LOGIN_VALIDATE_SUCCESS";
export const PIN_LOGIN_VALIDATE_FAILURE: "PIN_LOGIN_VALIDATE_FAILURE" =
  "PIN_LOGIN_VALIDATE_FAILURE";

// Profile
export const PROFILE_LOAD_REQUEST: "PROFILE_LOAD_REQUEST" =
  "PROFILE_LOAD_REQUEST";
export const PROFILE_LOAD_SUCCESS: "PROFILE_LOAD_SUCCESS" =
  "PROFILE_LOAD_SUCCESS";
export const PROFILE_LOAD_FAILURE: "PROFILE_LOAD_FAILURE" =
  "PROFILE_LOAD_FAILURE";

export const PROFILE_UPSERT_REQUEST: "PROFILE_UPSERT_REQUEST" =
  "PROFILE_UPSERT_REQUEST";
export const PROFILE_UPSERT_SUCCESS: "PROFILE_UPSERT_SUCCESS" =
  "PROFILE_UPSERT_SUCCESS";
export const PROFILE_UPSERT_FAILURE: "PROFILE_UPSERT_FAILURE" =
  "PROFILE_UPSERT_FAILURE";

// Wallet
// (transactions)
export const FETCH_TRANSACTIONS_REQUEST: "FETCH_TRANSACTIONS_REQUEST" =
  "FETCH_TRANSACTIONS_REQUEST";
export const TRANSACTIONS_FETCHED: "TRANSACTIONS_FETCHED" =
  "TRANSACTIONS_FETCHED";
export const SELECT_TRANSACTION_FOR_DETAILS: "SELECT_TRANSACTION_FOR_DETAILS" =
  "SELECT_TRANSACTION_FOR_DETAILS";
// (cards)
export const FETCH_CARDS_REQUEST: "FETCH_CARDS_REQUEST" = "FETCH_CARDS_REQUEST";
export const CARDS_FETCHED: "CARDS_FETCHED" = "CARDS_FETCHED";
export const SELECT_CARD_FOR_DETAILS: "SELECT_CARD_FOR_DETAILS" =
  "SELECT_CARD_FOR_DETAILS";
export const SET_FAVORITE_CARD: "SET_FAVORITE_CARD" = "SET_FAVORITE_CARD";
export const START_PAYMENT: "START_PAYMENT" = "START_PAYMENT";

// Messages
export const MESSAGES_LOAD_REQUEST: "MESSAGES_LOAD_REQUEST" =
  "MESSAGES_LOAD_REQUEST";
export const MESSAGES_LOAD_CANCEL: "MESSAGES_LOAD_CANCEL" =
  "MESSAGES_LOAD_CANCEL";
export const MESSAGES_LOAD_SUCCESS: "MESSAGES_LOAD_SUCCESS" =
  "MESSAGES_LOAD_SUCCESS";
export const MESSAGES_LOAD_FAILURE: "MESSAGES_LOAD_FAILURE" =
  "MESSAGES_LOAD_FAILURE";
export const MESSAGE_LOAD_SUCCESS: "MESSAGE_LOAD_SUCCESS" =
  "MESSAGE_LOAD_SUCCESS";

// Services
export const SERVICE_LOAD_SUCCESS: "SERVICE_LOAD_SUCCESS" =
  "SERVICE_LOAD_SUCCESS";

// BackendInfo

export const BACKEND_INFO_LOAD_SUCCESS: "BACKEND_INFO_LOAD_SUCCESS" =
  "BACKEND_INFO_LOAD_SUCCESS";

export const BACKEND_INFO_LOAD_FAILURE: "BACKEND_INFO_LOAD_FAILURE" =
  "BACKEND_INFO_LOAD_FAILURE";

// Error
export const ERROR_CLEAR: "ERROR_CLEAR" = "ERROR_CLEAR";

// Enum for actions that need UI state reducers
export const enum FetchRequestActions {
  TOS_ACCEPT = "TOS_ACCEPT",
  PIN_CREATE = "PIN_CREATE",
  PROFILE_LOAD = "PROFILE_LOAD",
  PROFILE_UPSERT = "PROFILE_UPSERT",
  MESSAGES_LOAD = "MESSAGES_LOAD"
}

// Extract keys from object and create a new union type
export type FetchRequestActionsType = keyof typeof FetchRequestActions;
