const BPD_ROUTES = {
  MAIN: "MAIN",

  ONBOARDING: {
    LOAD_CHECK_ACTIVATION_STATUS: "LOAD_CHECK_ACTIVATION_STATUS",
    INFORMATION_TOS: "INFORMATION_TOS",
    ELIGIBILITY_LOAD: "ELIGIBILITY_LOAD",
    ELIGIBILITY_KO_UNDERAGE: "ELIGIBILITY_KO_UNDERAGE",
    RESIDENCE_DECLARATION: "RESIDENCE_DECLARATION",
    RESIDENCE_KO_NOT_ITALIAN: "RESIDENCE_KO_NOT_ITALIAN",
    LOAD_ACTIVATE_BPD: "LOAD_ACTIVATE_BPD",
    ENROLL_PAYMENT_METHOD: "ENROLL_PAYMENT_METHOD",
    NO_PAYMENT_METHOD: "NO_PAYMENT_METHOD"
  },
  IBAN: {}
};

export default BPD_ROUTES;
