const BPD_ROUTES = {
  MAIN: "BPD_ROUTES_MAIN",

  ONBOARDING: {
    LOAD_CHECK_ACTIVATION_STATUS: "BPD_LOAD_CHECK_ACTIVATION_STATUS",
    INFORMATION_TOS: "BPD_INFORMATION_TOS",
    DECLARATION: "BPD_DECLARATION",
    LOAD_ACTIVATE_BPD: "BPD_LOAD_ACTIVATE_BPD",
    ENROLL_PAYMENT_METHODS: "BPD_ENROLL_PAYMENT_METHODS",
    NO_PAYMENT_METHODS: "BPD_NO_PAYMENT_METHODS"
  },
  IBAN: "BPD_IBAN"
};

export default BPD_ROUTES;
