# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.233.1"

default_platform :ios

platform :ios do
  before_all do
    setup_ci()
  end

  # Temporary disables automatic code signing so the matched profile is used.
  # @param build_configuration [String] Xcode signing settings (e.g. "Release", "Canary").
  # @param profile_name [String] Name of the matched provisioning profile to sign the build with (e.g. "match AppStore it.pagopa.app.io").
  private_lane :disable_automatic_code_signing do |options|
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "IO.xcodeproj",
      team_id: "M2X5YQ4BJ7",
      targets: ["IO"],
      build_configurations: [options[:build_configuration]],
      profile_name: options[:profile_name],
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
    )
  end

  # Generates the changelog from every commit since the last tag ending with
  # @param tag_suffix [String] Release type which can be a release candidate or a canary (e.g. "rc", "canary").
  private_lane :changelog_since_last_tag do |options|
    previous_tag = sh("git tag --sort=-taggerdate | grep \\\\-#{options[:tag_suffix]}\\\\. | sed -n '2 p' | tr -d '\n'")

    changelog_from_git_commits(
      tag_match_pattern: "*" + previous_tag + "*",
      pretty: "- %s",
      merge_commit_filtering: "exclude_merges"
    )
  end

  # Authenticates with the App Store Connect API key, returning it so it can
  # be reused by `sync_code_signing`/`pilot`. Requires `setup_ci` (run in
  # `before_all`) so the CI keychain is ready for credential access.
  private_lane :authenticate_app_store_connect do
    app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_API_KEY_ISSUER_ID']}",
      key_filepath: "./fastlane/AuthKey_#{ENV['APP_STORE_API_KEY_ID']}.p8",
      duration: 1200,
    )
  end

  desc "Submit a new Beta Build to TestFlight"
  lane :beta_circleci_testflight do |options|

    # xCode 14.2, prevents altool to fail with error "Could not
    # determine the package’s bundle ID" during the "pilot" step
    # See https://github.com/fastlane/fastlane/issues/20741
    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false'

    # use the App Store API Key to authenticate
    api_key = authenticate_app_store_connect

    sync_code_signing(type: "appstore", api_key: api_key)

    # Install pods
    cocoapods

    # Temporary disables automatic code signing to avoid issues during build
    disable_automatic_code_signing(
      build_configuration: "Release",
      profile_name: "match AppStore it.pagopa.app.io"
    )

    # build the app
    gym(
      scheme: "IO",
      clean: true,
      export_method: "app-store",
      workspace: "IO.xcworkspace",
      include_symbols: false
    )

    # generate the changelog based on last commits
    changelog = changelog_since_last_tag(tag_suffix: "rc")

    # upload to App store
    pilot(
      api_key: api_key,
      changelog: changelog,
      # max wait for App Store Connect processing (30 min)
      wait_processing_timeout_duration: 1800
    )
  end

  desc "Submit a new Canary Build to TestFlight"
  lane :canary_ci_testflight do |options|
    app_identifier = "it.pagopa.app.io.canary"
    # xCode 14.2, prevents altool to fail with error "Could not
    # determine the package’s bundle ID" during the "pilot" step
    # See https://github.com/fastlane/fastlane/issues/20741
    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false'

    # use the App Store API Key to authenticate
    api_key = authenticate_app_store_connect

    sync_code_signing(type: "appstore", app_identifier: app_identifier, api_key: api_key)

    # Install pods
    cocoapods

    # Temporary disables automatic code signing to avoid issues during build
    disable_automatic_code_signing(
      build_configuration: "Canary",
      profile_name: "match AppStore it.pagopa.app.io.canary"
    )

    # build the app
    gym(
      scheme: "IO",
      clean: true,
      export_method: "app-store",
      configuration: "Canary",
      workspace: "IO.xcworkspace",
      include_symbols: false
    )

    # generate the changelog based on last commits
    changelog = changelog_since_last_tag(tag_suffix: "canary")

    # upload to App store
    pilot(
      app_identifier: app_identifier,
      api_key: api_key,
      changelog: changelog,
      # max wait for App Store Connect processing (30 min)
      wait_processing_timeout_duration: 1800
    )
  end

  desc "Distribute previously uploaded beta to TestFlight, using GA"
  lane :distribute_beta_testflight do |options|

    # use the App Store API Key to authenticate
    api_key = authenticate_app_store_connect

    # upload to App store
    pilot(
      api_key: api_key,
      distribute_only: true,
      distribute_external: true,
      notify_external_testers: true,
      app_platform: "ios",
      groups: ["pagopa_beta_ios", "send_beta_ios", "ioproduct_beta_ios", "iomixpanel_beta_ios", "qa_beta_ios"],
      # max wait for App Store Connect processing (30 min)
      wait_processing_timeout_duration: 1800
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
