export const IdPayPaymentRoutes = {
  IDPAY_PAYMENT_MAIN: "IDPAY_PAYMENT_MAIN",
  IDPAY_PAYMENT_CODE_SCAN: "IDPAY_PAYMENT_CODE_SCAN",
  IDPAY_PAYMENT_CODE_INPUT: "IDPAY_PAYMENT_CODE_INPUT",
  IDPAY_PAYMENT_AUTHORIZATION: "IDPAY_PAYMENT_AUTHORIZATION",
  IDPAY_PAYMENT_RESULT: "IDPAY_PAYMENT_RESULT"
} as const;
