// flow-typed signature: 43db03b83dda7e27daccd93bd3d70122
// flow-typed version: <<STUB>>/native-base_v^2.3.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'native-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'native-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'native-base/__tests__/basic/Badge.android' {
  declare module.exports: any;
}

declare module 'native-base/__tests__/basic/Badge.ios' {
  declare module.exports: any;
}

declare module 'native-base/__tests__/basic/Button.android' {
  declare module.exports: any;
}

declare module 'native-base/__tests__/basic/Button.ios' {
  declare module.exports: any;
}

declare module 'native-base/__tests__/basic/Header.android' {
  declare module.exports: any;
}

declare module 'native-base/__tests__/basic/Header.ios' {
  declare module.exports: any;
}

declare module 'native-base/addEjectScript' {
  declare module.exports: any;
}

declare module 'native-base/dist/__tests__/basic/Badge.android' {
  declare module.exports: any;
}

declare module 'native-base/dist/__tests__/basic/Badge.ios' {
  declare module.exports: any;
}

declare module 'native-base/dist/__tests__/basic/Button.android' {
  declare module.exports: any;
}

declare module 'native-base/dist/__tests__/basic/Button.ios' {
  declare module.exports: any;
}

declare module 'native-base/dist/__tests__/basic/Header.android' {
  declare module.exports: any;
}

declare module 'native-base/dist/__tests__/basic/Header.ios' {
  declare module.exports: any;
}

declare module 'native-base/dist/addEjectScript' {
  declare module.exports: any;
}

declare module 'native-base/dist/ejectTheme' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Actionsheet' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Badge' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Base/NativeBaseComponent' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Body' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Button' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Card' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/CardItem' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Checkbox' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Container' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Content' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/DeckSwiper' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Drawer/index' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Fab' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Footer' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/FooterTab' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Form' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Gravatar' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/H1' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/H2' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/H3' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Header' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Icon/index' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/IconNB' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Input' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/InputGroup' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Item' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Label' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Left' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/List' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/ListItem' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Picker.android' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Picker.ios' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/PickerItem' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Radio' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Right' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Root' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Segment' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Separator' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Spinner' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Subtitle' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/SwipeRow' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Switch' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tab' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/TabContainer' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/TabHeading' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/Button.android' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/Button.ios' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/Button.windows' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/DefaultTabBar' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/index' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/SceneComponent' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/ScrollableTabBar' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Tabs/StaticContainer' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Text' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Textarea' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Thumbnail' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Title' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/Toast' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/ToastContainer' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/basic/View' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/index' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/init' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Badge' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Body' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Button' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Card' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/CardItem' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/CheckBox' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Container' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Content' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Fab' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Footer' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/FooterTab' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Form' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/H1' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/H2' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/H3' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Header' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Icon' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/index' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Input' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/InputGroup' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Item' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Label' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Left' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/ListItem' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Picker.android' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Picker.ios' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Radio' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Right' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Segment' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Separator' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Spinner' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Subtitle' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/SwipeRow' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Switch' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Tab' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/TabBar' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/TabContainer' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/TabHeading' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Text' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Textarea' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Thumbnail' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Title' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/Toast' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/components/View' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/variables/commonColor' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/variables/material' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/theme/variables/platform' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/Utils/computeProps' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/Utils/index' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/Utils/interactionManager' {
  declare module.exports: any;
}

declare module 'native-base/dist/src/Utils/mapPropsToStyleNames' {
  declare module.exports: any;
}

declare module 'native-base/ejectTheme' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Actionsheet' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Badge' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Base/NativeBaseComponent' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Body' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Button' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Card' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/CardItem' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Checkbox' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Container' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Content' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/DeckSwiper' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Drawer/index' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Fab' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Footer' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/FooterTab' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Form' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Gravatar' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/H1' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/H2' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/H3' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Header' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Icon/index' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/IconNB' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Input' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/InputGroup' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Item' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Label' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Left' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/List' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/ListItem' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Picker.android' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Picker.ios' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/PickerItem' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Radio' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Right' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Root' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Segment' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Separator' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Spinner' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Subtitle' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/SwipeRow' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Switch' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tab' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/TabContainer' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/TabHeading' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/Button.android' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/Button.ios' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/Button.windows' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/DefaultTabBar' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/index' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/SceneComponent' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/ScrollableTabBar' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Tabs/StaticContainer' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Text' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Textarea' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Thumbnail' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Title' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/Toast' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/ToastContainer' {
  declare module.exports: any;
}

declare module 'native-base/src/basic/View' {
  declare module.exports: any;
}

declare module 'native-base/src/index' {
  declare module.exports: any;
}

declare module 'native-base/src/init' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Badge' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Body' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Button' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Card' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/CardItem' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/CheckBox' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Container' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Content' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Fab' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Footer' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/FooterTab' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Form' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/H1' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/H2' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/H3' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Header' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Icon' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/index' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Input' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/InputGroup' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Item' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Label' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Left' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/ListItem' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Picker.android' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Picker.ios' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Radio' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Right' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Segment' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Separator' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Spinner' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Subtitle' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/SwipeRow' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Switch' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Tab' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/TabBar' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/TabContainer' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/TabHeading' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Text' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Textarea' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Thumbnail' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Title' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/Toast' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/components/View' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/variables/commonColor' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/variables/material' {
  declare module.exports: any;
}

declare module 'native-base/src/theme/variables/platform' {
  declare module.exports: any;
}

declare module 'native-base/src/Utils/computeProps' {
  declare module.exports: any;
}

declare module 'native-base/src/Utils/index' {
  declare module.exports: any;
}

declare module 'native-base/src/Utils/interactionManager' {
  declare module.exports: any;
}

declare module 'native-base/src/Utils/mapPropsToStyleNames' {
  declare module.exports: any;
}

// Filename aliases
declare module 'native-base/__tests__/basic/Badge.android.js' {
  declare module.exports: $Exports<'native-base/__tests__/basic/Badge.android'>;
}
declare module 'native-base/__tests__/basic/Badge.ios.js' {
  declare module.exports: $Exports<'native-base/__tests__/basic/Badge.ios'>;
}
declare module 'native-base/__tests__/basic/Button.android.js' {
  declare module.exports: $Exports<'native-base/__tests__/basic/Button.android'>;
}
declare module 'native-base/__tests__/basic/Button.ios.js' {
  declare module.exports: $Exports<'native-base/__tests__/basic/Button.ios'>;
}
declare module 'native-base/__tests__/basic/Header.android.js' {
  declare module.exports: $Exports<'native-base/__tests__/basic/Header.android'>;
}
declare module 'native-base/__tests__/basic/Header.ios.js' {
  declare module.exports: $Exports<'native-base/__tests__/basic/Header.ios'>;
}
declare module 'native-base/addEjectScript.js' {
  declare module.exports: $Exports<'native-base/addEjectScript'>;
}
declare module 'native-base/dist/__tests__/basic/Badge.android.js' {
  declare module.exports: $Exports<'native-base/dist/__tests__/basic/Badge.android'>;
}
declare module 'native-base/dist/__tests__/basic/Badge.ios.js' {
  declare module.exports: $Exports<'native-base/dist/__tests__/basic/Badge.ios'>;
}
declare module 'native-base/dist/__tests__/basic/Button.android.js' {
  declare module.exports: $Exports<'native-base/dist/__tests__/basic/Button.android'>;
}
declare module 'native-base/dist/__tests__/basic/Button.ios.js' {
  declare module.exports: $Exports<'native-base/dist/__tests__/basic/Button.ios'>;
}
declare module 'native-base/dist/__tests__/basic/Header.android.js' {
  declare module.exports: $Exports<'native-base/dist/__tests__/basic/Header.android'>;
}
declare module 'native-base/dist/__tests__/basic/Header.ios.js' {
  declare module.exports: $Exports<'native-base/dist/__tests__/basic/Header.ios'>;
}
declare module 'native-base/dist/addEjectScript.js' {
  declare module.exports: $Exports<'native-base/dist/addEjectScript'>;
}
declare module 'native-base/dist/ejectTheme.js' {
  declare module.exports: $Exports<'native-base/dist/ejectTheme'>;
}
declare module 'native-base/dist/src/basic/Actionsheet.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Actionsheet'>;
}
declare module 'native-base/dist/src/basic/Badge.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Badge'>;
}
declare module 'native-base/dist/src/basic/Base/NativeBaseComponent.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Base/NativeBaseComponent'>;
}
declare module 'native-base/dist/src/basic/Body.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Body'>;
}
declare module 'native-base/dist/src/basic/Button.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Button'>;
}
declare module 'native-base/dist/src/basic/Card.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Card'>;
}
declare module 'native-base/dist/src/basic/CardItem.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/CardItem'>;
}
declare module 'native-base/dist/src/basic/Checkbox.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Checkbox'>;
}
declare module 'native-base/dist/src/basic/Container.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Container'>;
}
declare module 'native-base/dist/src/basic/Content.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Content'>;
}
declare module 'native-base/dist/src/basic/DeckSwiper.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/DeckSwiper'>;
}
declare module 'native-base/dist/src/basic/Drawer/index.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Drawer/index'>;
}
declare module 'native-base/dist/src/basic/Fab.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Fab'>;
}
declare module 'native-base/dist/src/basic/Footer.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Footer'>;
}
declare module 'native-base/dist/src/basic/FooterTab.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/FooterTab'>;
}
declare module 'native-base/dist/src/basic/Form.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Form'>;
}
declare module 'native-base/dist/src/basic/Gravatar.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Gravatar'>;
}
declare module 'native-base/dist/src/basic/H1.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/H1'>;
}
declare module 'native-base/dist/src/basic/H2.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/H2'>;
}
declare module 'native-base/dist/src/basic/H3.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/H3'>;
}
declare module 'native-base/dist/src/basic/Header.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Header'>;
}
declare module 'native-base/dist/src/basic/Icon/index.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Icon/index'>;
}
declare module 'native-base/dist/src/basic/IconNB.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/IconNB'>;
}
declare module 'native-base/dist/src/basic/Input.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Input'>;
}
declare module 'native-base/dist/src/basic/InputGroup.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/InputGroup'>;
}
declare module 'native-base/dist/src/basic/Item.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Item'>;
}
declare module 'native-base/dist/src/basic/Label.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Label'>;
}
declare module 'native-base/dist/src/basic/Left.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Left'>;
}
declare module 'native-base/dist/src/basic/List.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/List'>;
}
declare module 'native-base/dist/src/basic/ListItem.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/ListItem'>;
}
declare module 'native-base/dist/src/basic/Picker.android.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Picker.android'>;
}
declare module 'native-base/dist/src/basic/Picker.ios.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Picker.ios'>;
}
declare module 'native-base/dist/src/basic/PickerItem.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/PickerItem'>;
}
declare module 'native-base/dist/src/basic/Radio.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Radio'>;
}
declare module 'native-base/dist/src/basic/Right.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Right'>;
}
declare module 'native-base/dist/src/basic/Root.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Root'>;
}
declare module 'native-base/dist/src/basic/Segment.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Segment'>;
}
declare module 'native-base/dist/src/basic/Separator.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Separator'>;
}
declare module 'native-base/dist/src/basic/Spinner.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Spinner'>;
}
declare module 'native-base/dist/src/basic/Subtitle.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Subtitle'>;
}
declare module 'native-base/dist/src/basic/SwipeRow.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/SwipeRow'>;
}
declare module 'native-base/dist/src/basic/Switch.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Switch'>;
}
declare module 'native-base/dist/src/basic/Tab.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tab'>;
}
declare module 'native-base/dist/src/basic/TabContainer.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/TabContainer'>;
}
declare module 'native-base/dist/src/basic/TabHeading.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/TabHeading'>;
}
declare module 'native-base/dist/src/basic/Tabs/Button.android.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/Button.android'>;
}
declare module 'native-base/dist/src/basic/Tabs/Button.ios.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/Button.ios'>;
}
declare module 'native-base/dist/src/basic/Tabs/Button.windows.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/Button.windows'>;
}
declare module 'native-base/dist/src/basic/Tabs/DefaultTabBar.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/DefaultTabBar'>;
}
declare module 'native-base/dist/src/basic/Tabs/index.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/index'>;
}
declare module 'native-base/dist/src/basic/Tabs/SceneComponent.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/SceneComponent'>;
}
declare module 'native-base/dist/src/basic/Tabs/ScrollableTabBar.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/ScrollableTabBar'>;
}
declare module 'native-base/dist/src/basic/Tabs/StaticContainer.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Tabs/StaticContainer'>;
}
declare module 'native-base/dist/src/basic/Text.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Text'>;
}
declare module 'native-base/dist/src/basic/Textarea.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Textarea'>;
}
declare module 'native-base/dist/src/basic/Thumbnail.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Thumbnail'>;
}
declare module 'native-base/dist/src/basic/Title.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Title'>;
}
declare module 'native-base/dist/src/basic/Toast.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/Toast'>;
}
declare module 'native-base/dist/src/basic/ToastContainer.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/ToastContainer'>;
}
declare module 'native-base/dist/src/basic/View.js' {
  declare module.exports: $Exports<'native-base/dist/src/basic/View'>;
}
declare module 'native-base/dist/src/index.js' {
  declare module.exports: $Exports<'native-base/dist/src/index'>;
}
declare module 'native-base/dist/src/init.js' {
  declare module.exports: $Exports<'native-base/dist/src/init'>;
}
declare module 'native-base/dist/src/theme/components/Badge.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Badge'>;
}
declare module 'native-base/dist/src/theme/components/Body.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Body'>;
}
declare module 'native-base/dist/src/theme/components/Button.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Button'>;
}
declare module 'native-base/dist/src/theme/components/Card.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Card'>;
}
declare module 'native-base/dist/src/theme/components/CardItem.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/CardItem'>;
}
declare module 'native-base/dist/src/theme/components/CheckBox.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/CheckBox'>;
}
declare module 'native-base/dist/src/theme/components/Container.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Container'>;
}
declare module 'native-base/dist/src/theme/components/Content.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Content'>;
}
declare module 'native-base/dist/src/theme/components/Fab.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Fab'>;
}
declare module 'native-base/dist/src/theme/components/Footer.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Footer'>;
}
declare module 'native-base/dist/src/theme/components/FooterTab.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/FooterTab'>;
}
declare module 'native-base/dist/src/theme/components/Form.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Form'>;
}
declare module 'native-base/dist/src/theme/components/H1.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/H1'>;
}
declare module 'native-base/dist/src/theme/components/H2.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/H2'>;
}
declare module 'native-base/dist/src/theme/components/H3.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/H3'>;
}
declare module 'native-base/dist/src/theme/components/Header.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Header'>;
}
declare module 'native-base/dist/src/theme/components/Icon.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Icon'>;
}
declare module 'native-base/dist/src/theme/components/index.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/index'>;
}
declare module 'native-base/dist/src/theme/components/Input.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Input'>;
}
declare module 'native-base/dist/src/theme/components/InputGroup.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/InputGroup'>;
}
declare module 'native-base/dist/src/theme/components/Item.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Item'>;
}
declare module 'native-base/dist/src/theme/components/Label.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Label'>;
}
declare module 'native-base/dist/src/theme/components/Left.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Left'>;
}
declare module 'native-base/dist/src/theme/components/ListItem.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/ListItem'>;
}
declare module 'native-base/dist/src/theme/components/Picker.android.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Picker.android'>;
}
declare module 'native-base/dist/src/theme/components/Picker.ios.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Picker.ios'>;
}
declare module 'native-base/dist/src/theme/components/Radio.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Radio'>;
}
declare module 'native-base/dist/src/theme/components/Right.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Right'>;
}
declare module 'native-base/dist/src/theme/components/Segment.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Segment'>;
}
declare module 'native-base/dist/src/theme/components/Separator.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Separator'>;
}
declare module 'native-base/dist/src/theme/components/Spinner.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Spinner'>;
}
declare module 'native-base/dist/src/theme/components/Subtitle.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Subtitle'>;
}
declare module 'native-base/dist/src/theme/components/SwipeRow.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/SwipeRow'>;
}
declare module 'native-base/dist/src/theme/components/Switch.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Switch'>;
}
declare module 'native-base/dist/src/theme/components/Tab.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Tab'>;
}
declare module 'native-base/dist/src/theme/components/TabBar.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/TabBar'>;
}
declare module 'native-base/dist/src/theme/components/TabContainer.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/TabContainer'>;
}
declare module 'native-base/dist/src/theme/components/TabHeading.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/TabHeading'>;
}
declare module 'native-base/dist/src/theme/components/Text.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Text'>;
}
declare module 'native-base/dist/src/theme/components/Textarea.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Textarea'>;
}
declare module 'native-base/dist/src/theme/components/Thumbnail.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Thumbnail'>;
}
declare module 'native-base/dist/src/theme/components/Title.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Title'>;
}
declare module 'native-base/dist/src/theme/components/Toast.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/Toast'>;
}
declare module 'native-base/dist/src/theme/components/View.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/components/View'>;
}
declare module 'native-base/dist/src/theme/variables/commonColor.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/variables/commonColor'>;
}
declare module 'native-base/dist/src/theme/variables/material.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/variables/material'>;
}
declare module 'native-base/dist/src/theme/variables/platform.js' {
  declare module.exports: $Exports<'native-base/dist/src/theme/variables/platform'>;
}
declare module 'native-base/dist/src/Utils/computeProps.js' {
  declare module.exports: $Exports<'native-base/dist/src/Utils/computeProps'>;
}
declare module 'native-base/dist/src/Utils/index.js' {
  declare module.exports: $Exports<'native-base/dist/src/Utils/index'>;
}
declare module 'native-base/dist/src/Utils/interactionManager.js' {
  declare module.exports: $Exports<'native-base/dist/src/Utils/interactionManager'>;
}
declare module 'native-base/dist/src/Utils/mapPropsToStyleNames.js' {
  declare module.exports: $Exports<'native-base/dist/src/Utils/mapPropsToStyleNames'>;
}
declare module 'native-base/ejectTheme.js' {
  declare module.exports: $Exports<'native-base/ejectTheme'>;
}
declare module 'native-base/src/basic/Actionsheet.js' {
  declare module.exports: $Exports<'native-base/src/basic/Actionsheet'>;
}
declare module 'native-base/src/basic/Badge.js' {
  declare module.exports: $Exports<'native-base/src/basic/Badge'>;
}
declare module 'native-base/src/basic/Base/NativeBaseComponent.js' {
  declare module.exports: $Exports<'native-base/src/basic/Base/NativeBaseComponent'>;
}
declare module 'native-base/src/basic/Body.js' {
  declare module.exports: $Exports<'native-base/src/basic/Body'>;
}
declare module 'native-base/src/basic/Button.js' {
  declare module.exports: $Exports<'native-base/src/basic/Button'>;
}
declare module 'native-base/src/basic/Card.js' {
  declare module.exports: $Exports<'native-base/src/basic/Card'>;
}
declare module 'native-base/src/basic/CardItem.js' {
  declare module.exports: $Exports<'native-base/src/basic/CardItem'>;
}
declare module 'native-base/src/basic/Checkbox.js' {
  declare module.exports: $Exports<'native-base/src/basic/Checkbox'>;
}
declare module 'native-base/src/basic/Container.js' {
  declare module.exports: $Exports<'native-base/src/basic/Container'>;
}
declare module 'native-base/src/basic/Content.js' {
  declare module.exports: $Exports<'native-base/src/basic/Content'>;
}
declare module 'native-base/src/basic/DeckSwiper.js' {
  declare module.exports: $Exports<'native-base/src/basic/DeckSwiper'>;
}
declare module 'native-base/src/basic/Drawer/index.js' {
  declare module.exports: $Exports<'native-base/src/basic/Drawer/index'>;
}
declare module 'native-base/src/basic/Fab.js' {
  declare module.exports: $Exports<'native-base/src/basic/Fab'>;
}
declare module 'native-base/src/basic/Footer.js' {
  declare module.exports: $Exports<'native-base/src/basic/Footer'>;
}
declare module 'native-base/src/basic/FooterTab.js' {
  declare module.exports: $Exports<'native-base/src/basic/FooterTab'>;
}
declare module 'native-base/src/basic/Form.js' {
  declare module.exports: $Exports<'native-base/src/basic/Form'>;
}
declare module 'native-base/src/basic/Gravatar.js' {
  declare module.exports: $Exports<'native-base/src/basic/Gravatar'>;
}
declare module 'native-base/src/basic/H1.js' {
  declare module.exports: $Exports<'native-base/src/basic/H1'>;
}
declare module 'native-base/src/basic/H2.js' {
  declare module.exports: $Exports<'native-base/src/basic/H2'>;
}
declare module 'native-base/src/basic/H3.js' {
  declare module.exports: $Exports<'native-base/src/basic/H3'>;
}
declare module 'native-base/src/basic/Header.js' {
  declare module.exports: $Exports<'native-base/src/basic/Header'>;
}
declare module 'native-base/src/basic/Icon/index.js' {
  declare module.exports: $Exports<'native-base/src/basic/Icon/index'>;
}
declare module 'native-base/src/basic/IconNB.js' {
  declare module.exports: $Exports<'native-base/src/basic/IconNB'>;
}
declare module 'native-base/src/basic/Input.js' {
  declare module.exports: $Exports<'native-base/src/basic/Input'>;
}
declare module 'native-base/src/basic/InputGroup.js' {
  declare module.exports: $Exports<'native-base/src/basic/InputGroup'>;
}
declare module 'native-base/src/basic/Item.js' {
  declare module.exports: $Exports<'native-base/src/basic/Item'>;
}
declare module 'native-base/src/basic/Label.js' {
  declare module.exports: $Exports<'native-base/src/basic/Label'>;
}
declare module 'native-base/src/basic/Left.js' {
  declare module.exports: $Exports<'native-base/src/basic/Left'>;
}
declare module 'native-base/src/basic/List.js' {
  declare module.exports: $Exports<'native-base/src/basic/List'>;
}
declare module 'native-base/src/basic/ListItem.js' {
  declare module.exports: $Exports<'native-base/src/basic/ListItem'>;
}
declare module 'native-base/src/basic/Picker.android.js' {
  declare module.exports: $Exports<'native-base/src/basic/Picker.android'>;
}
declare module 'native-base/src/basic/Picker.ios.js' {
  declare module.exports: $Exports<'native-base/src/basic/Picker.ios'>;
}
declare module 'native-base/src/basic/PickerItem.js' {
  declare module.exports: $Exports<'native-base/src/basic/PickerItem'>;
}
declare module 'native-base/src/basic/Radio.js' {
  declare module.exports: $Exports<'native-base/src/basic/Radio'>;
}
declare module 'native-base/src/basic/Right.js' {
  declare module.exports: $Exports<'native-base/src/basic/Right'>;
}
declare module 'native-base/src/basic/Root.js' {
  declare module.exports: $Exports<'native-base/src/basic/Root'>;
}
declare module 'native-base/src/basic/Segment.js' {
  declare module.exports: $Exports<'native-base/src/basic/Segment'>;
}
declare module 'native-base/src/basic/Separator.js' {
  declare module.exports: $Exports<'native-base/src/basic/Separator'>;
}
declare module 'native-base/src/basic/Spinner.js' {
  declare module.exports: $Exports<'native-base/src/basic/Spinner'>;
}
declare module 'native-base/src/basic/Subtitle.js' {
  declare module.exports: $Exports<'native-base/src/basic/Subtitle'>;
}
declare module 'native-base/src/basic/SwipeRow.js' {
  declare module.exports: $Exports<'native-base/src/basic/SwipeRow'>;
}
declare module 'native-base/src/basic/Switch.js' {
  declare module.exports: $Exports<'native-base/src/basic/Switch'>;
}
declare module 'native-base/src/basic/Tab.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tab'>;
}
declare module 'native-base/src/basic/TabContainer.js' {
  declare module.exports: $Exports<'native-base/src/basic/TabContainer'>;
}
declare module 'native-base/src/basic/TabHeading.js' {
  declare module.exports: $Exports<'native-base/src/basic/TabHeading'>;
}
declare module 'native-base/src/basic/Tabs/Button.android.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/Button.android'>;
}
declare module 'native-base/src/basic/Tabs/Button.ios.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/Button.ios'>;
}
declare module 'native-base/src/basic/Tabs/Button.windows.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/Button.windows'>;
}
declare module 'native-base/src/basic/Tabs/DefaultTabBar.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/DefaultTabBar'>;
}
declare module 'native-base/src/basic/Tabs/index.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/index'>;
}
declare module 'native-base/src/basic/Tabs/SceneComponent.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/SceneComponent'>;
}
declare module 'native-base/src/basic/Tabs/ScrollableTabBar.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/ScrollableTabBar'>;
}
declare module 'native-base/src/basic/Tabs/StaticContainer.js' {
  declare module.exports: $Exports<'native-base/src/basic/Tabs/StaticContainer'>;
}
declare module 'native-base/src/basic/Text.js' {
  declare module.exports: $Exports<'native-base/src/basic/Text'>;
}
declare module 'native-base/src/basic/Textarea.js' {
  declare module.exports: $Exports<'native-base/src/basic/Textarea'>;
}
declare module 'native-base/src/basic/Thumbnail.js' {
  declare module.exports: $Exports<'native-base/src/basic/Thumbnail'>;
}
declare module 'native-base/src/basic/Title.js' {
  declare module.exports: $Exports<'native-base/src/basic/Title'>;
}
declare module 'native-base/src/basic/Toast.js' {
  declare module.exports: $Exports<'native-base/src/basic/Toast'>;
}
declare module 'native-base/src/basic/ToastContainer.js' {
  declare module.exports: $Exports<'native-base/src/basic/ToastContainer'>;
}
declare module 'native-base/src/basic/View.js' {
  declare module.exports: $Exports<'native-base/src/basic/View'>;
}
declare module 'native-base/src/index.js' {
  declare module.exports: $Exports<'native-base/src/index'>;
}
declare module 'native-base/src/init.js' {
  declare module.exports: $Exports<'native-base/src/init'>;
}
declare module 'native-base/src/theme/components/Badge.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Badge'>;
}
declare module 'native-base/src/theme/components/Body.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Body'>;
}
declare module 'native-base/src/theme/components/Button.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Button'>;
}
declare module 'native-base/src/theme/components/Card.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Card'>;
}
declare module 'native-base/src/theme/components/CardItem.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/CardItem'>;
}
declare module 'native-base/src/theme/components/CheckBox.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/CheckBox'>;
}
declare module 'native-base/src/theme/components/Container.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Container'>;
}
declare module 'native-base/src/theme/components/Content.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Content'>;
}
declare module 'native-base/src/theme/components/Fab.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Fab'>;
}
declare module 'native-base/src/theme/components/Footer.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Footer'>;
}
declare module 'native-base/src/theme/components/FooterTab.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/FooterTab'>;
}
declare module 'native-base/src/theme/components/Form.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Form'>;
}
declare module 'native-base/src/theme/components/H1.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/H1'>;
}
declare module 'native-base/src/theme/components/H2.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/H2'>;
}
declare module 'native-base/src/theme/components/H3.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/H3'>;
}
declare module 'native-base/src/theme/components/Header.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Header'>;
}
declare module 'native-base/src/theme/components/Icon.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Icon'>;
}
declare module 'native-base/src/theme/components/index.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/index'>;
}
declare module 'native-base/src/theme/components/Input.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Input'>;
}
declare module 'native-base/src/theme/components/InputGroup.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/InputGroup'>;
}
declare module 'native-base/src/theme/components/Item.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Item'>;
}
declare module 'native-base/src/theme/components/Label.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Label'>;
}
declare module 'native-base/src/theme/components/Left.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Left'>;
}
declare module 'native-base/src/theme/components/ListItem.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/ListItem'>;
}
declare module 'native-base/src/theme/components/Picker.android.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Picker.android'>;
}
declare module 'native-base/src/theme/components/Picker.ios.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Picker.ios'>;
}
declare module 'native-base/src/theme/components/Radio.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Radio'>;
}
declare module 'native-base/src/theme/components/Right.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Right'>;
}
declare module 'native-base/src/theme/components/Segment.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Segment'>;
}
declare module 'native-base/src/theme/components/Separator.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Separator'>;
}
declare module 'native-base/src/theme/components/Spinner.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Spinner'>;
}
declare module 'native-base/src/theme/components/Subtitle.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Subtitle'>;
}
declare module 'native-base/src/theme/components/SwipeRow.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/SwipeRow'>;
}
declare module 'native-base/src/theme/components/Switch.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Switch'>;
}
declare module 'native-base/src/theme/components/Tab.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Tab'>;
}
declare module 'native-base/src/theme/components/TabBar.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/TabBar'>;
}
declare module 'native-base/src/theme/components/TabContainer.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/TabContainer'>;
}
declare module 'native-base/src/theme/components/TabHeading.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/TabHeading'>;
}
declare module 'native-base/src/theme/components/Text.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Text'>;
}
declare module 'native-base/src/theme/components/Textarea.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Textarea'>;
}
declare module 'native-base/src/theme/components/Thumbnail.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Thumbnail'>;
}
declare module 'native-base/src/theme/components/Title.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Title'>;
}
declare module 'native-base/src/theme/components/Toast.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/Toast'>;
}
declare module 'native-base/src/theme/components/View.js' {
  declare module.exports: $Exports<'native-base/src/theme/components/View'>;
}
declare module 'native-base/src/theme/variables/commonColor.js' {
  declare module.exports: $Exports<'native-base/src/theme/variables/commonColor'>;
}
declare module 'native-base/src/theme/variables/material.js' {
  declare module.exports: $Exports<'native-base/src/theme/variables/material'>;
}
declare module 'native-base/src/theme/variables/platform.js' {
  declare module.exports: $Exports<'native-base/src/theme/variables/platform'>;
}
declare module 'native-base/src/Utils/computeProps.js' {
  declare module.exports: $Exports<'native-base/src/Utils/computeProps'>;
}
declare module 'native-base/src/Utils/index.js' {
  declare module.exports: $Exports<'native-base/src/Utils/index'>;
}
declare module 'native-base/src/Utils/interactionManager.js' {
  declare module.exports: $Exports<'native-base/src/Utils/interactionManager'>;
}
declare module 'native-base/src/Utils/mapPropsToStyleNames.js' {
  declare module.exports: $Exports<'native-base/src/Utils/mapPropsToStyleNames'>;
}
