// flow-typed signature: be6c9ca373e0e7d9c94aec68cc24c205
// flow-typed version: <<STUB>>/option_v^0.2.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'option'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'option' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'option/test/options.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'option/index' {
  declare module.exports: $Exports<'option'>;
}
declare module 'option/index.js' {
  declare module.exports: $Exports<'option'>;
}
declare module 'option/test/options.test.js' {
  declare module.exports: $Exports<'option/test/options.test'>;
}
