// flow-typed signature: 1579c037030f7ddeb33c5b2bcaa53c78
// flow-typed version: <<STUB>>/react-native-fs_v^2.9/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fs/FS.common' {
  declare module.exports: any;
}

declare module 'react-native-fs/IntegrationTests/FSTest' {
  declare module.exports: any;
}

declare module 'react-native-fs/IntegrationTests/IntegrationTestHarnessTest' {
  declare module.exports: any;
}

declare module 'react-native-fs/IntegrationTests/IntegrationTestsApp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fs/FS.common.js' {
  declare module.exports: $Exports<'react-native-fs/FS.common'>;
}
declare module 'react-native-fs/IntegrationTests/FSTest.js' {
  declare module.exports: $Exports<'react-native-fs/IntegrationTests/FSTest'>;
}
declare module 'react-native-fs/IntegrationTests/IntegrationTestHarnessTest.js' {
  declare module.exports: $Exports<'react-native-fs/IntegrationTests/IntegrationTestHarnessTest'>;
}
declare module 'react-native-fs/IntegrationTests/IntegrationTestsApp.js' {
  declare module.exports: $Exports<'react-native-fs/IntegrationTests/IntegrationTestsApp'>;
}
