// flow-typed signature: 50a879fe1b4ddd4fed18c4da9a6e1f46
// flow-typed version: <<STUB>>/react-native-offline_v^3.7.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-offline/src/__tests__/createNetworkMiddleware.spec' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/__tests__/reducer.spec' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/actionCreators' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/actionTypes' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/checkConnectivityInterval' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/checkInternetAccess' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/ConnectivityRenderer' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/createNetworkMiddleware' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/index' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/makeHttpRequest' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/reactConnectionStore' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/reducer' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/sagas' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/types' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/withNetworkConnectivity' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-offline/src/__tests__/createNetworkMiddleware.spec.js' {
  declare module.exports: $Exports<'react-native-offline/src/__tests__/createNetworkMiddleware.spec'>;
}
declare module 'react-native-offline/src/__tests__/reducer.spec.js' {
  declare module.exports: $Exports<'react-native-offline/src/__tests__/reducer.spec'>;
}
declare module 'react-native-offline/src/actionCreators.js' {
  declare module.exports: $Exports<'react-native-offline/src/actionCreators'>;
}
declare module 'react-native-offline/src/actionTypes.js' {
  declare module.exports: $Exports<'react-native-offline/src/actionTypes'>;
}
declare module 'react-native-offline/src/checkConnectivityInterval.js' {
  declare module.exports: $Exports<'react-native-offline/src/checkConnectivityInterval'>;
}
declare module 'react-native-offline/src/checkInternetAccess.js' {
  declare module.exports: $Exports<'react-native-offline/src/checkInternetAccess'>;
}
declare module 'react-native-offline/src/ConnectivityRenderer.js' {
  declare module.exports: $Exports<'react-native-offline/src/ConnectivityRenderer'>;
}
declare module 'react-native-offline/src/createNetworkMiddleware.js' {
  declare module.exports: $Exports<'react-native-offline/src/createNetworkMiddleware'>;
}
declare module 'react-native-offline/src/index.js' {
  declare module.exports: $Exports<'react-native-offline/src/index'>;
}
declare module 'react-native-offline/src/makeHttpRequest.js' {
  declare module.exports: $Exports<'react-native-offline/src/makeHttpRequest'>;
}
declare module 'react-native-offline/src/reactConnectionStore.js' {
  declare module.exports: $Exports<'react-native-offline/src/reactConnectionStore'>;
}
declare module 'react-native-offline/src/reducer.js' {
  declare module.exports: $Exports<'react-native-offline/src/reducer'>;
}
declare module 'react-native-offline/src/sagas.js' {
  declare module.exports: $Exports<'react-native-offline/src/sagas'>;
}
declare module 'react-native-offline/src/types.js' {
  declare module.exports: $Exports<'react-native-offline/src/types'>;
}
declare module 'react-native-offline/src/withNetworkConnectivity.js' {
  declare module.exports: $Exports<'react-native-offline/src/withNetworkConnectivity'>;
}
