// flow-typed signature: 74b4587b2a3c1187ce33324af2b22d13
// flow-typed version: <<STUB>>/react-native-easy-grid_v^0.1.8/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-easy-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-easy-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-easy-grid/Components/Col' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/Grid' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Components/Row' {
  declare module.exports: any;
}

declare module 'react-native-easy-grid/Utils/computeProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-easy-grid/Components/Col.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/Col'>;
}
declare module 'react-native-easy-grid/Components/Grid.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/Grid'>;
}
declare module 'react-native-easy-grid/Components/Row.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Components/Row'>;
}
declare module 'react-native-easy-grid/index' {
  declare module.exports: $Exports<'react-native-easy-grid'>;
}
declare module 'react-native-easy-grid/index.js' {
  declare module.exports: $Exports<'react-native-easy-grid'>;
}
declare module 'react-native-easy-grid/Utils/computeProps.js' {
  declare module.exports: $Exports<'react-native-easy-grid/Utils/computeProps'>;
}
