// flow-typed signature: 0b978d49362f9b357d715b427b0fdd74
// flow-typed version: <<STUB>>/react-native-sha256_v^1.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sha256'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sha256' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sha256/sha256' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sha256/sha256.js' {
  declare module.exports: $Exports<'react-native-sha256/sha256'>;
}
