// flow-typed signature: d2dd31d8bc95567a19a9f6a82aef494c
// flow-typed version: <<STUB>>/react-native-mixpanel_v^0.0.16/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mixpanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mixpanel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-mixpanel/index' {
  declare module.exports: $Exports<'react-native-mixpanel'>;
}
declare module 'react-native-mixpanel/index.js' {
  declare module.exports: $Exports<'react-native-mixpanel'>;
}
