const ROUTES = {
  HOME: 'HOME',
  PROFILE: 'PROFILE',
  DIGITALADDRESS: 'DIGITAL_ADDRESS',
  TOPICSSELECTION: 'TOPICS_SELECTION',
  SENDERSELECTION: 'SENDER_SELECTION',
}

module.exports = {
  ROUTES
}
