export enum ITW_DISCOVERY_ACTIONS_EVENTS {
  ITW_ID_START = "ITW_ID_START",
  ITW_INTRO_BACK = "ITW_INTRO_BACK",
  ITW_DISCOVERY_PLUS = "ITW_DISCOVERY_PLUS",
  ITW_TOS_ACCEPTED = "ITW_TOS_ACCEPTED"
}

export enum ITW_DISCOVERY_ERRORS_EVENTS {
  ITW_ALREADY_ACTIVATED = "ITW_ALREADY_ACTIVATED",
  ITW_NFC_NOT_SUPPORTED = "ITW_NFC_NOT_SUPPORTED"
}
