const ZENDESK_ROUTES = {
  MAIN: "ZENDESK_MAIN",
  HELP_CENTER: "ZENDESK_HELP_CENTER",
  PANIC_MODE: "ZENDESK_PANIC_MODE",
  ASK_PERMISSIONS: "ZENDESK_ASK_PERMISSIONS",
  CHOOSE_CATEGORY: "ZENDESK_CHOOSE_CATEGORY",
  CHOOSE_SUB_CATEGORY: "ZENDESK_CHOOSE_SUB_CATEGORY"
} as const;

export default ZENDESK_ROUTES;
