const ZENDESK_ROUTES = {
  MAIN: "ZENDESK_MAIN",
  HELP_CENTER: "ZENDESK_HELP_CENTER",
  ASK_PERMISSIONS: "ZENDESK_ASK_PERMISSIONS",
  CHOOSE_CATEGORY: "ZENDESK_CHOOSE_CATEGORY",
  CHOOSE_SUB_CATEGORY: "ZENDESK_CHOOSE_SUB_CATEGORY"
};

export default ZENDESK_ROUTES;
