export const AUTHENTICATION_ROUTES = {
  // Authentication
  MAIN: "AUTHENTICATION",
  LANDING: "AUTHENTICATION_LANDING",
  ROOTED_DEVICE: "AUTHENTICATION_ROOTED_DEVICE",
  OPT_IN: "AUTHENTICATION_OPT_IN",
  IDP_SELECTION: "AUTHENTICATION_IDP_SELECTION",
  IDP_LOGIN: "AUTHENTICATION_IDP_LOGIN",
  AUTH_SESSION: "AUTHENTICATION_AUTH_SESSION",
  IDP_TEST: "AUTHENTICATION_IDP_TEST",
  CIE_NOT_INSTALLED: "CIE_NOT_INSTALLED",
  CIE_ACTIVATE_NFC_SCREEN: "CIE_ACTIVATE_NFC_SCREEN",
  AUTH_ERROR_SCREEN: "AUTH_ERROR_SCREEN",
  UNLOCK_ACCESS_SCREEN: "UNLOCK_ACCESS_SCREEN",
  CIE_ID_LOGIN: "AUTHENTICATION_CIE_ID_LOGIN",
  CIE_ID_WIZARD: "AUTHENTICATION_CIE_ID_WIZARD",
  CIE_PIN_WIZARD: "AUTHENTICATION_CIE_PIN_WIZARD",
  SPID_WIZARD: "AUTHENTICATION_SPID_WIZARD",
  ID_ACTIVATION_WIZARD: "AUTHENTICATION_ID_ACTIVATION_WIZARD",
  CIE_ID_ERROR: "AUTHENTICATION_CIE_ID_ERROR",
  CIE_ID_INCORRECT_URL: "AUTHENTICATION_CIE_ID_INCORRECT_URL",

  // CIE
  CIE_EXPIRED_SCREEN: "CIE_EXPIRED_SCREEN",
  CIE_PIN_SCREEN: "CIE_PIN_SCREEN",
  CIE_LOGIN_CONFIG_SCREEN: "CIE_LOGIN_CONFIG_SCREEN",
  CIE_CARD_READER_SCREEN: "CIE_CARD_READER_SCREEN",
  CIE_CONSENT_DATA_USAGE: "CIE_CONSENT_DATA_USAGE",
  CIE_WRONG_PIN_SCREEN: "CIE_WRONG_PIN_SCREEN",
  CIE_UNEXPECTED_ERROR: "CIE_UNEXPECTED_ERROR",
  CIE_EXTENDED_APDU_NOT_SUPPORTED_SCREEN:
    "CIE_EXTENDED_APDU_NOT_SUPPORTED_SCREEN",
  CIE_WRONG_CARD_SCREEN: "CIE_WRONG_CARD_SCREEN",

  // Active session login
  LANDING_ACTIVE_SESSION_LOGIN: "LANDING_ACTIVE_SESSION_LOGIN",
  IDP_ACTIVE_SESSION_LOGIN: "AUTHENTICATION_ACTIVE_SESSION_IDP_LOGIN",
  CIE_ID_ACTIVE_SESSION_LOGIN: "CIE_ID_ACTIVE_SESSION_LOGIN",
  CIE_CONSENT_DATA_USAGE_ACTIVE_SESSION_LOGIN:
    "CIE_CONSENT_DATA_USAGE_ACTIVE_SESSION_LOGIN",
  CIE_CARD_READER_SCREEN_ACTIVE_SESSION_LOGIN:
    "CIE_CARD_READER_SCREEN_ACTIVE_SESSION_LOGIN",
  IDP_LOGIN_ACTIVE_SESSION_LOGIN:
    "AUTHENTICATION_IDP_LOGIN_ACTIVE_SESSION_LOGIN"
} as const;
