export const PaymentsBarcodeRoutes = {
  PAYMENT_BARCODE_NAVIGATOR: "PAYMENT_BARCODE_NAVIGATOR",
  PAYMENT_BARCODE_SCAN: "PAYMENT_BARCODE_SCAN",
  PAYMENT_BARCODE_CHOICE: "PAYMENT_BARCODE_CHOICE"
} as const;
