export const PaymentsBarcodeRoutes = {
  PAYMENTS_BARCODE_NAVIGATOR: "PAYMENTS_BARCODE_NAVIGATOR",
  PAYMENTS_BARCODE_SCAN: "PAYMENTS_BARCODE_SCAN",
  PAYMENTS_BARCODE_CHOICE: "PAYMENTS_BARCODE_CHOICE"
} as const;
