export const FCI_ROUTES = {
  MAIN: "FCI_MAIN",
  ROUTER: "FCI_ROUTER",
  DOCUMENTS: "FCI_DOCUMENTS",
  SIGNATURE_FIELDS: "FCI_SIGNATURE_FIELDS",
  USER_DATA_SHARE: "FCI_USER_DATA_SHARE",
  QTSP_TOS: "FCI_QTSP_TOS",
  DOC_PREVIEW: "FCI_DOC_PREVIEW",
  TYP: "FCI_TYP",
  SIGNATURE_REQUESTS: "FCI_SIGNATURE_REQUESTS",
  SIGNATURE_DETAIL_REQUEST_ERROR: "FCI_SIGNATURE_DETAIL_REQUEST_ERROR"
} as const;
