export const FCI_ROUTES = {
  MAIN: "FCI_MAIN",
  ROUTER: "FCI_ROUTER",
  DOCUMENTS: "FCI_DOCUMENTS",
  SIGNATURES_LIST: "FCI_SIGNATURES_LIST",
  USER_DATA_SHARE: "FCI_USER_DATA_SHARE",
  QTSP_TOS: "FCI_QTSP_TOS",
  TYP: "FCI_TYP"
} as const;
