import { NavigatorScreenParams } from "@react-navigation/native";
import { EmailInsertScreenNavigationParams } from "../../../userData/shared/screens/EmailInsertScreen";
import { SendEmailValidationScreenProp } from "../../../userData/shared/screens/EmailValidationSendEmailScreen";
import { SETTINGS_ROUTES } from "../routes";
import { AuthenticationParamsList } from "../../../../authentication/common/navigation/params/AuthenticationParamsList";

export type SettingsParamsList = {
  [SETTINGS_ROUTES.PROFILE_PRIVACY_MAIN]: undefined;
  [SETTINGS_ROUTES.PROFILE_PRIVACY]: undefined;
  [SETTINGS_ROUTES.PROFILE_PRIVACY_SHARE_DATA]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_HOME]: undefined;
  [SETTINGS_ROUTES.PROFILE_DATA]: undefined;
  [SETTINGS_ROUTES.PROFILE_SECURITY]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_SERVICES]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_APPEARANCE]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_EMAIL_FORWARDING]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_CALENDAR]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_LANGUAGE]: undefined;
  [SETTINGS_ROUTES.PROFILE_ABOUT_APP]: undefined;
  [SETTINGS_ROUTES.PROFILE_LOGOUT]: undefined;
  [SETTINGS_ROUTES.PROFILE_FISCAL_CODE]: undefined;
  [SETTINGS_ROUTES.INSERT_EMAIL_SCREEN]: EmailInsertScreenNavigationParams;
  [SETTINGS_ROUTES.EMAIL_VERIFICATION_SCREEN]: SendEmailValidationScreenProp;
  [SETTINGS_ROUTES.PIN_SCREEN]: undefined;
  [SETTINGS_ROUTES.PROFILE_DOWNLOAD_DATA]: undefined;
  [SETTINGS_ROUTES.DESIGN_SYSTEM]: undefined;
  [SETTINGS_ROUTES.LOLLIPOP_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.PROFILE_REMOVE_ACCOUNT_INFO]: undefined;
  [SETTINGS_ROUTES.PROFILE_REMOVE_ACCOUNT_DETAILS]: undefined;
  [SETTINGS_ROUTES.PROFILE_REMOVE_ACCOUNT_SUCCESS]: undefined;
  [SETTINGS_ROUTES.CGN_LANDING_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.TRIALS_SYSTEM_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.PROFILE_PREFERENCES_NOTIFICATIONS]: undefined;
  [SETTINGS_ROUTES.IDPAY_ONBOARDING_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.IDPAY_CODE_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.IO_MARKDOWN_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.APP_FEEDBACK_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.CIE_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.NFC_PLAYGROUND]: undefined;
  [SETTINGS_ROUTES.SETTINGS_MAIN]: undefined;
  [SETTINGS_ROUTES.AUTHENTICATION]: NavigatorScreenParams<AuthenticationParamsList>;
};
