import WALLET_ONBOARDING_BANCOMAT_ROUTES from "./routes";

export type PaymentMethodOnboardingBancomatParamsList = {
  [WALLET_ONBOARDING_BANCOMAT_ROUTES.BANCOMAT_START]: undefined;
  [WALLET_ONBOARDING_BANCOMAT_ROUTES.CHOOSE_BANK]: undefined;
  [WALLET_ONBOARDING_BANCOMAT_ROUTES.SEARCH_AVAILABLE_USER_BANCOMAT]: undefined;
  [WALLET_ONBOARDING_BANCOMAT_ROUTES.SUGGEST_BPD_ACTIVATION]: undefined;
};
