const WALLET_ONBOARDING_BANCOMAT_ROUTES = {
  MAIN: "WALLET_ONBOARDING_BANCOMAT_MAIN",

  BANCOMAT_START: "WALLET_ONBOARDING_BANCOMAT_START",
  CHOOSE_BANK: "WALLET_ONBOARDING_CHOOSE_BANK_SCREEN",
  SEARCH_AVAILABLE_USER_BANCOMAT:
    "WALLET_ONBOARDING_BANCOMAT_SEARCH_AVAILABLE_USER_BANCOMAT",

  SUGGEST_BPD_ACTIVATION: "WALLET_ONBOARDING_BANCOMAT_SUGGEST_BPD_ACTIVATION",
  ACTIVATE_BPD_NEW_BANCOMAT: "WALLET_ONBOARDING_BANCOMAT_ACTIVATE_BPD_NEW",
  ACTIVATE_BPD_NEW_CREDIT_CARD: "WALLET_ONBOARDING_CREDIT_CARD_ACTIVATE_BPD_NEW"
} as const;

export default WALLET_ONBOARDING_BANCOMAT_ROUTES;
