const WALLET_ADD_BANCOMAT_ROUTES = {
  MAIN: "WALLET_ADD_BANCOMAT_MAIN",

  CHOOSE_BANK: "WALLET_ADD_BANCOMAT_CHOOSE_BANK",
  SEARCH_AVAILABLE_USER_BANCOMAT:
    "WALLET_ADD_BANCOMAT_SEARCH_AVAILABLE_USER_BANCOMAT",
  ADD_BANCOMAT: "WALLET_ADD_BANCOMAT"
};

export default WALLET_ADD_BANCOMAT_ROUTES;
