const WALLET_ADD_BANCOMAT_ROUTES = {
  MAIN: "WALLET_ADD_BANCOMAT_MAIN",

  CHOOSE_BANK: "WALLET_ADD_BANCOMAT_CHOOSE_BANK",
  ADD_BANCOMAT: "WALLET_ADD_BANCOMAT",
  POC1: "WALLET_ADD_BANCOMAT_POC1"
};

export default WALLET_ADD_BANCOMAT_ROUTES;
