export const PaymentsReceiptRoutes = {
  PAYMENT_RECEIPT_NAVIGATOR: "PAYMENT_RECEIPT_NAVIGATOR",
  PAYMENT_RECEIPT_DETAILS: "PAYMENT_RECEIPT_DETAILS",
  PAYMENT_RECEIPT_CART_ITEM_DETAILS: "PAYMENT_RECEIPT_CART_ITEM_DETAILS",
  PAYMENT_RECEIPT_LIST_SCREEN: "PAYMENT_RECEIPT_LIST_SCREEN",
  PAYMENT_RECEIPT_PREVIEW_SCREEN: "PAYMENT_RECEIPT_PREVIEW_SCREEN",
  PAYMENT_RECEIPT_LOADING_SCREEN: "PAYMENT_RECEIPT_LOADING_SCREEN",
  PAYMENT_RECEIPT_ERROR_SCREEN: "PAYMENT_RECEIPT_ERROR_SCREEN"
} as const;
