export const PaymentsTransactionBizEventsRoutes = {
  PAYMENT_TRANSACTION_BIZ_EVENTS_NAVIGATOR:
    "PAYMENT_TRANSACTION_BIZ_EVENTS_NAVIGATOR",
  PAYMENT_TRANSACTION_BIZ_EVENTS_DETAILS:
    "PAYMENT_TRANSACTION_BIZ_EVENTS_DETAILS",
  PAYMENT_TRANSACTION_BIZ_EVENTS_OPERATION_DETAILS:
    "PAYMENT_TRANSACTION_BIZ_EVENTS_OPERATION_DETAILS",
  PAYMENT_TRANSACTION_BIZ_EVENTS_LIST_SCREEN:
    "PAYMENT_TRANSACTION_BIZ_EVENTS_LIST_SCREEN"
} as const;
