export const ITW_PLAYGROUND_ROUTES = {
  MAIN: "ITW_PLAYGROUND_MAIN",
  LANDING: "ITW_PLAYGROUND_LANDING",
  CREDENTIAL_DETAIL: "ITW_PLAYGROUND_CREDENTIAL_DETAIL",
  DEVICE_PERMISSIONS: "ITW_PLAYGROUND_PROXIMITY_DEVICE_PERMISSIONS",
  BLUETOOTH_ACTIVATION: "ITW_PLAYGROUND_PROXIMITY_BLUETOOTH_ACTIVATION"
} as const;
