export const ITW_PLAYGROUND_ROUTES = {
  LANDING: "ITW_PLAYGROUND_LANDING",
  CREDENTIAL_DETAIL: "ITW_PLAYGROUND_CREDENTIAL_DETAIL",
  DISCOVERY_INFO_NEW: "ITW_PLAYGROUND_DISCOVERY_INFO_NEW"
} as const;
