const CGN_ROUTES = {
  MAIN: "CGN_ROUTES_MAIN",

  ACTIVATION: {
    LOAD_CHECK_ACTIVATION_STATUS: "CGN_LOAD_CHECK_ACTIVATION_STATUS",
    INFORMATION_TOS: "CGN_INFORMATION_TOS",
    LOADING: "CGN_ACTIVATION_LOADING",
    EXISTS: "CGN_ACTIVATION_EXISTS",
    TIMEOUT: "CGN_ACTIVATION_TIMEOUT",
    INELIGIBLE: "CGN_ACTIVATION_INELIGIBLE",
    PENDING: "CGN_ACTIVATION_PENDING",
    COMPLETED: "CGN_ACTIVATION_COMPLETED"
  },

  DETAILS: "CGN_DETAILS",
  CTA_START_CGN: "CTA_START_CGN"
};

export default CGN_ROUTES;
