const CGN_ROUTES = {
  ACTIVATION: {
    MAIN: "CGN_ACTIVATION_MAIN",
    LOAD_CHECK_ACTIVATION_STATUS: "CGN_LOAD_CHECK_ACTIVATION_STATUS",
    INFORMATION_TOS: "CGN_INFORMATION_TOS",
    LOADING: "CGN_ACTIVATION_LOADING",
    EXISTS: "CGN_ACTIVATION_EXISTS",
    TIMEOUT: "CGN_ACTIVATION_TIMEOUT",
    INELIGIBLE: "CGN_ACTIVATION_INELIGIBLE",
    PENDING: "CGN_ACTIVATION_PENDING",
    COMPLETED: "CGN_ACTIVATION_COMPLETED",
    CTA_START_CGN: "CTA_START_CGN"
  },
  EYCA: {
    ACTIVATION: {
      MAIN: "CGN_EYCA_MAIN",
      LOADING: "CGN_EYCA_ACTIVATION_LOADING"
    }
  },
  DETAILS: {
    MAIN: "CGN_DETAILS_MAIN",
    DETAILS: "CGN_DETAILS",
    DETAILS_OTP: "CGN_DETAILS_OTP",
    MERCHANTS: {
      LIST: "CGN_MERCHANTS_LIST",
      TABS: "CGN_MERCHANTS_TABS",
      DETAIL: "CGN_MERCHANTS_DETAIL",
      LANDING_WEBVIEW: "CGN_MERCHANTS_LANDING_WEBVIEW"
    }
  }
};

export default CGN_ROUTES;
