const WALLET_ONBOARDING_COBADGE_ROUTES = {
  MAIN: "WALLET_ONBOARDING_COBADGE_MAIN",

  CHOOSE_TYPE: "WALLET_ONBOARDING_COBADGE_CHOOSE_TYPE",

  START: "WALLET_ONBOARDING_COBADGE_START",
  SEARCH_AVAILABLE: "WALLET_ONBOARDING_COBADGE_SEARCH_AVAILABLE"
} as const;

export default WALLET_ONBOARDING_COBADGE_ROUTES;
