export const IdPayConfigurationRoutes = {
  IDPAY_CONFIGURATION_NAVIGATOR: "IDPAY_CONFIGURATION_NAVIGATOR",
  IDPAY_CONFIGURATION_INTRO: "IDPAY_CONFIGURATION_INTRO",
  IDPAY_CONFIGURATION_IBAN_LANDING: "IDPAY_CONFIGURATION_IBAN_LANDING",
  IDPAY_CONFIGURATION_IBAN_ONBOARDING: "IDPAY_CONFIGURATION_IBAN_ONBOARDING",
  IDPAY_CONFIGURATION_IBAN_ENROLLMENT: "IDPAY_CONFIGURATION_IBAN_ENROLLMENT",
  IDPAY_CONFIGURATION_INSTRUMENTS_ENROLLMENT:
    "IDPAY_CONFIGURATION_INSTRUMENTS_ENROLLMENT",
  IDPAY_CONFIGURATION_SUCCESS: "IDPAY_CONFIGURATION_SUCCESS",
  IDPAY_CONFIGURATION_DISCOUNT_INSTRUMENTS:
    "IDPAY_CONFIGURATION_DISCOUNT_INSTRUMENTS"
} as const;
