export enum States {
  AWAITING_TRX_CODE_INPUT = "AWAITING_TRX_CODE_INPUT",
  PRE_AUTHORIZING_PAYMENT = "PRE_AUTHORIZING_PAYMENT",
  AWAITING_PAYMENT_AUTHORIZATION = "AWAITING_PAYMENT_AUTHORIZATION",
  AUTHORIZING_PAYMENT = "AUTHORIZING_PAYMENT",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILURE = "PAYMENT_FAILURE"
}
