export enum States {
  AWAITING_PRE_AUTHORIZATION = "AWAITING_PRE_AUTHORIZATION",
  PRE_AUTHORIZING = "PRE_AUTHORIZING",
  LOADING_TRANSACTION_DATA = "LOADING_TRANSACTION_DATA",
  AWAITING_AUTHORIZATION = "AWAITING_AUTHORIZATION",
  AUTHORIZING = "AUTHORIZING_PAYMENT",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILURE = "PAYMENT_FAILURE"
}
