export const IdPayUnsubscriptionRoutes = {
  IDPAY_UNSUBSCRIPTION_NAVIGATOR: "IDPAY_UNSUBSCRIPTION_NAVIGATOR",
  IDPAY_UNSUBSCRIPTION_CONFIRMATION: "IDPAY_UNSUBSCRIPTION_CONFIRMATION",
  IDPAY_UNSUBSCRIPTION_RESULT: "IDPAY_UNSUBSCRIPTION_RESULT"
} as const;
