export enum InitiativeFailureType {
  GENERIC = "GENERIC",
  INITIATIVE_ERROR = "INITIATIVE_ERROR",
  IBAN_LIST_LOAD_FAILURE = "IBAN_LIST_LOAD_FAILURE",
  IBAN_ENROLL_FAILURE = "IBAN_ENROLL_FAILURE",
  INSTRUMENTS_LIST_LOAD_FAILURE = "INSTRUMENTS_LIST_LOAD_FAILURE",
  INSTRUMENT_ENROLL_FAILURE = "INSTRUMENT_ENROLL_FAILURE",
  INSTRUMENT_DELETE_FAILURE = "INSTRUMENT_DELETE_FAILURE"
}
