export const ITW_REMOTE_ROUTES = {
  MAIN: "ITW_REMOTE_MAIN",
  REQUEST_VALIDATION: "ITW_REMOTE_REQUEST_VALIDATION",
  CLAIMS_DISCLOSURE: "ITW_REMOTE_CLAIMS_DISCLOSURE",
  AUTH_RESPONSE: "ITW_REMOTE_AUTH_RESPONSE",
  FAILURE: "ITW_REMOTE_FAILURE"
} as const;
