export const CDC_ROUTES = {
  BONUS_REQUEST_MAIN: "CDC_BONUS_REQUEST_MAIN",
  INFORMATION_TOS: "CDC_INFORMATION_TOS",
  SELECT_BONUS_YEAR: "CDC_SELECT_BONUS_YEAR",
  SELECT_RESIDENCE: "CDC_SELECT_RESIDENCE",
  BONUS_REQUESTED: "CDC_BONUS_REQUESTED"
} as const;
