const X_PAGOPA_LOLLIPOP_PREFIX = "X-PagoPA-LolliPOP";

export const constants = {
  BASE64: "base64",
  COLON: ":",
  CONTENT_DIGEST_SHA256: "sha-256=:",
  CONTENT_DIGEST_VALIDATION_REGEX: "(.+)=:(.+):",
  HEADERS: {
    CONTENT_DIGEST: "Content-Digest"
  },
  SHA_256: "sha256",
  SIGNATURE_PREFIX: (d: number = 1) => `sig${d}=`,
  UTF8: "utf8",
  X_PAGOPA_LOLLIPOP_NONCE: `${X_PAGOPA_LOLLIPOP_PREFIX}-Nonce`,
  X_PAGOPA_LOLLIPOP_METHOD: `${X_PAGOPA_LOLLIPOP_PREFIX}-Method`,
  X_PAGOPA_LOLLIPOP_ORIGINAL_URL: `${X_PAGOPA_LOLLIPOP_PREFIX}-Original-URl`,
  X_PAGOPA_LOLLIPOP_ORIGINAL_AUTHORITY: `${X_PAGOPA_LOLLIPOP_PREFIX}-Authority`
} as const;
