const SV_ROUTES = {
  MAIN: "SV_ROUTES_MAIN",
  VOUCHER_GENERATION: {
    CHECK_STATUS: "SV_CHECK_STATUS",
    SELECT_BENEFICIARY_CATEGORY: "SV_SELECT_BENEFICIARY_CATEGORY"
  }
};

export default SV_ROUTES;
