const SV_ROUTES = {
  MAIN: "SV_ROUTES_MAIN",
  VOUCHER_GENERATION: {
    CHECK_STATUS: "SV_CHECK_STATUS",
    SELECT_BENEFICIARY_CATEGORY: "SV_SELECT_BENEFICIARY_CATEGORY",
    STUDENT_SELECT_DESTINATION: "SV_STUDENT_SELECT_DESTINATION",
    DISABLE_ADDITIONAL_INFO: "SV_DISABLE_ADDITIONAL_INFO",
    WORKER_CHECK_INCOME_THRESHOLD: "SV_WORKER_CHECK_INCOME_THRESHOLD",
    WORKER_SELECT_DESTINATION: "SV_WORKER_SELECT_DESTINATION",
    SICK_CHECK_INCOME_THRESHOLD: "SV_SICK_CHECK_INCOME_THRESHOLD",
    SICK_SELECT_DESTINATION: "SV_SICK_SELECT_DESTINATION"
  }
};

export default SV_ROUTES;
