const SV_ROUTES = {
  VOUCHER_GENERATION: {
    CHECK_STATUS: "SV_CHECK_STATUS",
    SELECT_BENEFICIARY_CATEGORY: "SV_SELECT_BENEFICIARY_CATEGORY",
    STUDENT_SELECT_DESTINATION: "SV_STUDENT_SELECT_DESTINATION",
    DISABLED_ADDITIONAL_INFO: "SV_DISABLED_ADDITIONAL_INFO",
    WORKER_CHECK_INCOME_THRESHOLD: "SV_WORKER_CHECK_INCOME_THRESHOLD",
    WORKER_SELECT_DESTINATION: "SV_WORKER_SELECT_DESTINATION",
    SICK_CHECK_INCOME_THRESHOLD: "SV_SICK_CHECK_INCOME_THRESHOLD",
    SICK_SELECT_DESTINATION: "SV_SICK_SELECT_DESTINATION",
    SELECT_FLIGHTS_DATA: "SV_SELECT_FLIGHTS_DATA",
    SUMMARY: "SV_SUMMARY",
    VOUCHER_GENERATED: "SV_VOUCHER_GENERATED",
    KO_CHECK_RESIDENCE: "SV_KO_CHECK_RESIDENCE",
    KO_SELECT_BENEFICIARY_CATEGORY: "SV_KO_SELECT_BENEFICIARY_CATEGORY",
    KO_CHECK_INCOME_THRESHOLD: "SV_KO_CHECK_INCOME_THRESHOLD",
    TIMEOUT_GENERATED_VOUCHER: "SV_TIMEOUT_GENERATED_VOUCHER"
  },
  VOUCHER_LIST: {
    LIST: "SV_VOUCHER_LIST",
    DETAILS: "SV_VOUCHER_DETAILS"
  }
};

export default SV_ROUTES;
