export enum ITW_OFFLINE_SCREENVIEW_EVENTS {
  ITW_OFFLINE_WALLET = "ITW_OFFLINE_WALLET",
  ITW_OFFLINE_BOTTOM_SHEET = "ITW_OFFLINE_BOTTOM_SHEET",
  ITW_OFFLINE_ACCESS_EXPIRING = "ITW_OFFLINE_ACCESS_EXPIRING",
  ITW_OFFLINE_ACCESS_EXPIRED = "ITW_OFFLINE_ACCESS_EXPIRED"
}

export enum ITW_OFFLINE_ACTIONS_EVENTS {
  ITW_OFFLINE_RICARICA_APP_IO = "ITW_OFFLINE_RICARICA_APP_IO"
}

export enum ITW_OFFLINE_ERRORS_EVENTS {
  ITW_OFFLINE_RELOAD_FAILURE = "ITW_OFFLINE_RELOAD_FAILURE"
}
