export enum ITW_OFFLINE_SCREENVIEW_EVENTS {
  ITW_OFFLINE_WALLET = "ITW_OFFLINE_WALLET",
  ITW_OFFLINE_BOTTOM_SHEET = "ITW_OFFLINE_BOTTOM_SHEET",
  ITW_OFFLINE_ACCESS_EXPIRING = "ITW_OFFLINE_ACCESS_EXPIRING",
  ITW_OFFLINE_ACCESS_EXPIRED = "ITW_OFFLINE_ACCESS_EXPIRED"
}
