import { InitiativeDataDTO } from "@io-app/api-types/generated/definitions/idpay/InitiativeDataDTO";

export enum IDPayInitiativeID {
  OK = 1,

  OK_INVITED,
  OK_NO_PREREQUISITES,
  OK_PDND_ONLY,
  OK_SELF_ONLY,
  OK_GUIDONIA,
  OK_BONUS_ELETTRODOMESTICI,

  KO_GENERIC,
  KO_NOT_STARTED,
  KO_ENDED,
  KO_BUDGET_EXHAUSTED,

  KO_STATUS_NO_REQUIREMENTS,
  KO_STATUS_NOT_IN_WHITELIST,
  KO_STATUS_ON_EVALUATION,
  KO_STATUS_NOT_ELIGIBLE,
  KO_STATUS_ONBOARDED,
  KO_STATUS_UNSUBSCRIBED,
  KO_ONBOARDING_WAITING_LIST,
  KO_FAMILY_UNIT_ALREADY_JOINED,
  KO_TOO_MANY_REQUESTS
}

export enum IDPayServiceID {
  OK = 1,

  OK_INVITED,
  OK_NO_PREREQUISITES,
  OK_PDND_ONLY,
  OK_SELF_ONLY,
  OK_GUIDONIA,
  OK_BONUS_ELETTRODOMESTICI,

  KO_GENERIC,
  KO_NOT_STARTED,
  KO_ENDED,
  KO_BUDGET_EXHAUSTED,

  KO_STATUS_NO_REQUIREMENTS,
  KO_STATUS_NOT_IN_WHITELIST,
  KO_STATUS_ON_EVALUATION,
  KO_STATUS_NOT_ELIGIBLE,
  KO_STATUS_ONBOARDED,
  KO_STATUS_UNSUBSCRIBED,
  KO_ONBOARDING_WAITING_LIST,
  KO_FAMILY_UNIT_ALREADY_JOINED,
  KO_TOO_MANY_REQUESTS
}

export type InitiativeDataDTOWithServiceId = InitiativeDataDTO & {
  serviceId: string;
};
