export const PaymentsOnboardingRoutes = {
  PAYMENT_ONBOARDING_NAVIGATOR: "PAYMENT_ONBOARDING_NAVIGATOR",
  PAYMENT_ONBOARDING_SELECT_METHOD: "PAYMENT_ONBOARDING_SELECT_METHOD",
  PAYMENT_ONBOARDING_RESULT_FEEDBACK: "PAYMENT_ONBOARDING_RESULT_FEEDBACK"
} as const;
