export const PaymentsOnboardingRoutes = {
  PAYMENTS_ONBOARDING_NAVIGATOR: "PAYMENTS_ONBOARDING_NAVIGATOR",
  PAYMENTS_ONBOARDING_SELECT_METHOD: "PAYMENTS_ONBOARDING_SELECT_METHOD",
  PAYMENTS_ONBOARDING_RESULT_FEEDBACK: "PAYMENTS_ONBOARDING_RESULT_FEEDBACK"
} as const;
