require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

target 'ItaliaApp' do
  config = use_native_modules!
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  use_react_native!(:path => config["reactNativePath"])

  target 'ItaliaAppTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
end

# Fix a open bug in react-native-config
# @see https://github.com/luggit/react-native-config/issues/125
post_install do |installer|
  flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
