require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

min_ios_versions_supported = ['12.4', min_ios_version_supported]  
index_of_max = min_ios_versions_supported.each_with_index.max_by { |number, _| number.to_f }[1]

platform :ios, min_ios_versions_supported[index_of_max] 

prepare_react_native_project!
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Required by react-native-permissions
# https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#ios
setup_permissions([
  'PhotoLibrary', # Required for Gallery read permission
])

production = ENV["PRODUCTION"] == "1"
# This env is used to check whether
# we are in a CI environment or not.
IS_CI = ENV['CI']

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = IS_CI ? FlipperConfiguration.disabled : FlipperConfiguration.enabled


# Flags change depending on the env values.
flags = get_default_flags()

target 'ItaliaApp' do
  config = use_native_modules!

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  pod 'ReactNativeART', :podspec => '../node_modules/@react-native-community/art/ReactNativeART.podspec'
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ItaliaAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
    )

    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'Flipper'
          file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
          contents = File.read(file_path)
          unless contents.include?('#include <functional>')
            File.open(file_path, 'w') do |file|
              file.puts('#include <functional>')
              file.puts(contents)
            end
          end
        end        
        # This is needed in order to build the project on Apple silicon.
      	# Beware that after this modification you need Rosetta to run the app 
      	# on the simulator.
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
