export const PaymentsPaymentRoutes = {
  PAYMENTS_PAYMENT_NAVIGATOR: "PAYMENTS_PAYMENT_NAVIGATOR",
  PAYMENTS_PAYMENT_INPUT_NOTICE_NUMBER: "PAYMENTS_PAYMENT_INPUT_NOTICE_NUMBER",
  PAYMENTS_PAYMENT_INPUT_FISCAL_CODE: "PAYMENTS_PAYMENT_INPUT_FISCAL_CODE",
  PAYMENTS_PAYMENT_DETAIL: "PAYMENTS_PAYMENT_DETAIL",
  PAYMENTS_PAYMENT_MAKE: "PAYMENTS_PAYMENT_MAKE",
  PAYMENTS_PAYMENT_OUTCOME: "PAYMENTS_PAYMENT_OUTCOME"
} as const;
