import WALLET_ONBOARDING_PRIVATIVE_ROUTES from "./routes";

export type PaymentMethodOnboardingPrivativeParamsList = {
  [WALLET_ONBOARDING_PRIVATIVE_ROUTES.CHOOSE_ISSUER]: undefined;
  [WALLET_ONBOARDING_PRIVATIVE_ROUTES.INSERT_CARD_NUMBER]: undefined;
  [WALLET_ONBOARDING_PRIVATIVE_ROUTES.DISABLED_ISSUER]: undefined;
  [WALLET_ONBOARDING_PRIVATIVE_ROUTES.UNAVAILABLE_ISSUER]: undefined;
  [WALLET_ONBOARDING_PRIVATIVE_ROUTES.SEARCH_AVAILABLE]: undefined;
};
