const WALLET_ONBOARDING_PRIVATIVE_ROUTES = {
  MAIN: "WALLET_ONBOARDING_PRIVATIVE_MAIN",

  CHOOSE_ISSUER: "WALLET_ONBOARDING_PRIVATIVE_CHOOSE_ISSUER",
  DISABLED_ISSUER: "WALLET_ONBOARDING_PRIVATIVE_DISABLED_ISSUER",
  UNAVAILABLE_ISSUER: "WALLET_ONBOARDING_PRIVATIVE_UNAVAILABLE_ISSUER",

  INSERT_CARD_NUMBER: "WALLET_ONBOARDING_PRIVATIVE_INSERT_CARD_NUMBER",

  SEARCH_AVAILABLE: "WALLET_ONBOARDING_PRIVATIVE_SEARCH_AVAILABLE",

  ACTIVATE_BPD_NEW: "WALLET_ONBOARDING_PRIVATIVE_ACTIVATE_BPD_NEW"
};

export default WALLET_ONBOARDING_PRIVATIVE_ROUTES;
