const PAYPAL_ROUTES = {
  ONBOARDING: {
    MAIN: "WALLET_ONBOARDING_PAYPAL_MAIN",
    START: "WALLET_ONBOARDING_PAYPAL_START",
    SEARCH_PSP: "WALLET_ONBOARDING_PAYPAL_SEARCH_PSP",
    CHECKOUT: "WALLET_ONBOARDING_PAYPAL_CHECKOUT",
    CHECKOUT_SUCCESS: "WALLET_ONBOARDING_PAYPAL_CHECKOUT_SUCCESS",
    CHECKOUT_FAILURE: "WALLET_ONBOARDING_PAYPAL_CHECKOUT_FAILURE"
  }
};

export default PAYPAL_ROUTES;
