const PAYPAL_ROUTES = {
  ONBOARDING: {
    MAIN: "WALLET_ONBOARDING_PAYPAL_MAIN",
    START: "WALLET_ONBOARDING_PAYPAL_START",
    SEARCH_PSP: "WALLET_ONBOARDING_PAYPAL_SEARCH_PSP",
    CHECKOUT: "WALLET_ONBOARDING_PAYPAL_CHECKOUT",
    CHECKOUT_COMPLETED: "WALLET_ONBOARDING_PAYPAL_CHECKOUT_COMPLETED"
  }
} as const;

export default PAYPAL_ROUTES;
