export enum OnboardingFailureType {
  GENERIC = "GENERIC",
  NOT_STARTED = "NOT_STARTED",
  ENDED = "ENDED",
  NO_BUDGET = "NO_BUDGET",
  SUSPENDED = "SUSPENDED",
  NO_PERMISSION = "NO_PERMISSION",
  ON_EVALUATION = "ON_EVALUATION",
  NOT_ELIGIBLE = "NOT_ELIGIBLE",
  ONBOARDED = "ONBOARDED",
  WITHDRAWED = "WITHDRAWED"
}
