export enum OnboardingFailure {
  GENERIC = "GENERIC",
  NOT_STARTED = "NOT_STARTED",
  ENDED = "ENDED",
  NO_BUDGET = "NO_BUDGET",
  SUSPENDED = "SUSPENDED",
  NO_REQUIREMENTS = "NO_REQUIREMENTS",
  ON_EVALUATION = "ON_EVALUATION",
  NOT_ELIGIBLE = "NOT_ELIGIBLE",
  ONBOARDED = "ONBOARDED",
  UNSUBSCRIBED = "UNSUBSCRIBED"
}
