info:
  title: Carta della Cultutra REST APIs
  description: API to request Carta della Cultura
  version: 0.0.1
paths:
  /beneficiario/stato:
    get:
      summary: Lettura stato beneficiario per ogni anno
      operationId: getStatoBeneficiario
      responses:
        '200':
          description: Stato Beneficiario per Anno
          schema:
            $ref: '#/definitions/ListaStatoPerAnno'
        '401':
          description: Utente non autorizzato
        '403':
          description: Utente non loggato
        '404':
          description: Risorsa non trovata
        '500':
          description: Errore interno.
      security:
        - BearerAuth: []
      parameters: []
      produces:
        - application/json
  /beneficiario/registrazione:
    post:
      tags:
        - /secured/utente
      summary: Richiesta Carta della Cultura da parte del beneficiario
      operationId: registraBeneficiario
      responses:
        '200':
          description: Richiesta OK per almeno un anno
          schema:
            $ref: '#/definitions/ListaEsitoRichiestaPerAnno'
        '400':
          description: Validazioni non superate
          schema:
            $ref: '#/definitions/RichiestaCartaErrata'
        '401':
          description: Utente non autorizzato
        '403':
          description: Utente non loggato
        '404':
          description: Risorsa non esiste
        '500':
          description: Errore interno.
      security:
        - BearerAuth: []
      parameters:
        - required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/AnniRiferimento'
      consumes:
        - application/json
      produces:
        - application/json
swagger: '2.0'
basePath: /$%7Bhost%7D
definitions:
  StatoBeneficiario:
    type: string
    enum:
      - ATTIVABILE
      - INATTIVABILE
      - ATTIVO
      - VALUTAZIONE
      - INATTIVO
  EsitoRichiesta:
    type: string
    enum:
      - INIZIATIVA_TERMINATA
      - ANNO_NON_AMMISSIBILE
      - CIT_REGISTRATO
      - OK
  Anno:
    type: string
    pattern: ^\\d{4}$
    description: Anno a quattro cifre
    example: '2000'
  AnnoIsee:
    type: object
    required:
      - anno
    properties:
      anno:
        $ref: '#/definitions/Anno'
      dataIsee:
        type: string
  RichiestaCartaErrataMotivo:
    type: string
    enum:
      - NO_INPUT
      - ANNI_RIFERIMENTO_NON_FORNITI
      - LISTA_ANNI_VUOTA
      - FORMATO_ANNI_ERRATO
  RichiestaCartaErrata:
    type: object
    required:
      - status
    properties:
      type:
        type: string
      title:
        type: string
      status:
        $ref: '#/definitions/RichiestaCartaErrataMotivo'
      detail:
        type: string
      instance:
        type: string
      errorCode:
        type: string
  StatoBeneficiarioPerAnno:
    type: object
    required:
      - statoBeneficiario
      - annoRiferimento
    properties:
      statoBeneficiario:
        $ref: '#/definitions/StatoBeneficiario'
      annoRiferimento:
        $ref: '#/definitions/Anno'
  EsitoRichiestaPerAnno:
    type: object
    required:
      - esitoRichiesta
      - annoRiferimento
    properties:
      esitoRichiesta:
        $ref: '#/definitions/EsitoRichiesta'
      annoRiferimento:
        $ref: '#/definitions/Anno'
  ListaStatoPerAnno:
    type: object
    required:
      - listaStatoPerAnno
    properties:
      listaStatoPerAnno:
        type: array
        items:
          $ref: '#/definitions/StatoBeneficiarioPerAnno'
  ListaEsitoRichiestaPerAnno:
    type: object
    required:
      - listaEsitoRichiestaPerAnno
    properties:
      listaEsitoRichiestaPerAnno:
        type: array
        items:
          $ref: '#/definitions/EsitoRichiestaPerAnno'
  AnniRiferimento:
    type: object
    required:
      - anniRif
    properties:
      anniRif:
        type: array
        items:
          $ref: '#/definitions/AnnoIsee'
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
x-components: {}
