export enum ITW_LIFECYCLE_ACTIONS_EVENTS {
  ITW_NEW_ID_RESET = "ITW_NEW_ID_RESET"
}

export enum ITW_LIFECYCLE_ERRORS_EVENTS {
  ITW_LOGIN_ID_NOT_MATCH = "ITW_LOGIN_ID_NOT_MATCH",
  ITW_STATUS_WALLET_ATTESTATION_FAILURE = "ITW_STATUS_WALLET_ATTESTATION_FAILURE",
  ITW_INSTANCE_REVOKED = "ITW_INSTANCE_REVOKED",
  ITW_BAD_STATE_WALLET_DEACTIVATED = "ITW_BAD_STATE_WALLET_DEACTIVATED"
}
