export const IdPayOnboardingRoutes = {
  IDPAY_ONBOARDING_MAIN: "IDPAY_ONBOARDING_MAIN",
  IDPAY_ONBOARDING_INITIATIVE_DETAILS: "IDPAY_ONBOARDING_INITIATIVE_DETAILS",
  IDPAY_ONBOARDING_ENABLE_MESSAGE: "IDPAY_ONBOARDING_ENABLE_MESSAGE",
  IDPAY_ONBOARDING_PDNDACCEPTANCE: "IDPAY_ONBOARDING_PDNDACCEPTANCE",
  IDPAY_ONBOARDING_BOOL_SELF_DECLARATIONS: "IDPAY_ONBOARDING_SELF_DECLARATIONS",
  IDPAY_ONBOARDING_COMPLETION: "IDPAY_ONBOARDING_COMPLETION",
  IDPAY_ONBOARDING_FAILURE: "IDPAY_ONBOARDING_FAILURE",
  IDPAY_ONBOARDING_MULTI_SELF_DECLARATIONS:
    "IDPAY_ONBOARDING_MULTI_SELF_DECLARATIONS",
  IDPAY_ONBOARDING_INPUT_FORM: "IDPAY_ONBOARDING_INPUT_FORM",
  IDPAY_ONBOARDING_ENABLE_NOTIFICATIONS:
    "IDPAY_ONBOARDING_ENABLE_NOTIFICATIONS",
  IDPAY_ONBOARDING_FAILURE_TO_RETRY: "IDPAY_ONBOARDING_FAILURE_TO_RETRY",
  IDPAY_ONBOARDING_LOADING: "IDPAY_ONBOARDING_LOADING"
} as const;
