export const SERVICES_ROUTES = {
  SERVICES_NAVIGATOR: "SERVICES_NAVIGATOR",
  SERVICES_HOME: "SERVICES_HOME",
  INSTITUTION_SERVICES: "INSTITUTION_SERVICES",
  SEARCH: "SEARCH",
  SERVICE_DETAIL: "SERVICE_DETAIL",
  SERVICE_FAVOURITES: "SERVICE_FAVOURITES"
} as const;
