import { ExpoCieNative } from "../native";
import { type LogMode } from "./types";

/**
 * Sets the log mode for the CIE SDK.
 *
 * **Note**: Logging is only supported on iOS. On Android, this method will
 * throw an error.
 *
 * @example
 *   ```typescript
 *   CieLogger.setLogMode("CONSOLE");
 *   ```;
 *
 * @param mode - The log mode to set ("ENABLED", "FILE", "CONSOLE", or
 *   "DISABLED").
 */
const setLogMode = (mode: LogMode) => {
  ExpoCieNative.setLogMode(mode);
};

/**
 * Retrieves the file path of the latest logs generated by the CIE SDK.
 *
 * @returns A promise that resolves to a string representing the file path of
 *   the latest logs.
 * @throws {CieError} If cannot retrieve the logs path.
 */
const getLogsFilePath = async (): Promise<string> =>
  ExpoCieNative.getLogsFilePath();

/**
 * Retrieves the contetent of the latest logs generated by the CIE SDK.
 *
 * @returns A promise that resolves to a string representing the content of the
 *   latest logs.
 * @throws {CieError} If cannot retrieve the logs content.
 */
const getLogs = async (): Promise<string> => ExpoCieNative.getLogs();

export { getLogs, getLogsFilePath, setLogMode };
