# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.5"

default_platform :ios

platform :ios do
  before_all do
    HOCKEYAPP_ALPHA_TOKEN = ENV["HOCKEYAPP_ALPHA_TOKEN"]
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Register new device"
  lane :register_new_device do  |options|
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(
                     devices: device_hash
                     )
    refresh_profiles
  end

  # A helper lane for refreshing provisioning profiles.
  lane :refresh_profiles do
    match(
      type: "development",
      force: true)
    match(
      type: "adhoc",
      force: true)
  end

  desc "Submit a new Beta Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number
    increment_build_number

    # make sure to update the provisioning profile if necessary
    # more information: https://codesigning.guide
    match(
      force_for_new_devices: true,
      type: "adhoc"
    )

    # build the app
    gym(
      scheme: "ItaliaApp",
      clean: true,
      export_method: "ad-hoc",
      # sdk: "iphoneos8.4",
    )

    # generate the changelog based on last commits
    changelog_from_git_commits

    versioning_paths = [
      "ItaliaApp.xcodeproj/project.pbxproj",
      "ItaliaApp/Info.plist",
      "ItaliaAppTests/Info.plist"
    ]
    git_add(path: versioning_paths)
    git_commit(path: versioning_paths, message: "New iOS beta build")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    # add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # upload to HockeyApp
    hockey(
      api_token: HOCKEYAPP_ALPHA_TOKEN
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
