const MVL_ROUTES = {
  MAIN: "MVL_ROUTES_MAIN",
  DETAILS: "MVL_DETAILS",
  CERTIFICATES: "MVL_CERTIFICATES",
  RECIPIENTS: "MVL_RECIPIENTS",
  SIGNATURE: "MVL_SIGNATURE"
};

export default MVL_ROUTES;
