export const PaymentsCheckoutRoutes = {
  PAYMENT_CHECKOUT_NAVIGATOR: "PAYMENT_CHECKOUT_NAVIGATOR",
  PAYMENT_CHECKOUT_INPUT_NOTICE_NUMBER: "PAYMENT_CHECKOUT_INPUT_NOTICE_NUMBER",
  PAYMENT_CHECKOUT_INPUT_FISCAL_CODE: "PAYMENT_CHECKOUT_INPUT_FISCAL_CODE",
  PAYMENT_CHECKOUT_DETAIL: "PAYMENT_CHECKOUT_DETAIL",
  PAYMENT_CHECKOUT_MAKE: "PAYMENT_CHECKOUT_MAKE",
  PAYMENT_CHECKOUT_OUTCOME: "PAYMENT_CHECKOUT_OUTCOME"
} as const;
