export const PaymentsCheckoutRoutes = {
  PAYMENTS_CHECKOUT_NAVIGATOR: "PAYMENTS_CHECKOUT_NAVIGATOR",
  PAYMENTS_CHECKOUT_INPUT_NOTICE_NUMBER:
    "PAYMENTS_CHECKOUT_INPUT_NOTICE_NUMBER",
  PAYMENTS_CHECKOUT_INPUT_FISCAL_CODE: "PAYMENTS_CHECKOUT_INPUT_FISCAL_CODE",
  PAYMENTS_CHECKOUT_DETAIL: "PAYMENTS_CHECKOUT_DETAIL",
  PAYMENTS_CHECKOUT_MAKE: "PAYMENTS_CHECKOUT_MAKE",
  PAYMENTS_CHECKOUT_OUTCOME: "PAYMENTS_CHECKOUT_OUTCOME"
} as const;
