export const PaymentsCheckoutRoutes = {
  PAYMENT_CHECKOUT_NAVIGATOR: "PAYMENT_CHECKOUT_NAVIGATOR",
  PAYMENT_CHECKOUT_INPUT_NOTICE_NUMBER: "PAYMENT_CHECKOUT_INPUT_NOTICE_NUMBER",
  PAYMENT_CHECKOUT_INPUT_FISCAL_CODE: "PAYMENT_CHECKOUT_INPUT_FISCAL_CODE",
  PAYMENT_NOTICE_SUMMARY: "PAYMENT_NOTICE_SUMMARY",
  PAYMENT_CHECKOUT_MAKE: "PAYMENT_CHECKOUT_MAKE",
  PAYMENT_CHECKOUT_OUTCOME: "PAYMENT_CHECKOUT_OUTCOME",
  PAYMENT_CHECKOUT_FAILURE: "PAYMENT_CHECKOUT_FAILURE",
  PAYMENT_CHECKOUT_WEB_VIEW: "PAYMENT_CHECKOUT_WEB_VIEW"
} as const;
