export const ITW_PROXIMITY_ROUTES = {
  DEVICE_PERMISSIONS: "ITW_PROXIMITY_DEVICE_PERMISSIONS",
  BLUETOOTH_ACTIVATION: "ITW_PROXIMITY_BLUETOOTH_ACTIVATION",
  CLAIMS_DISCLOSURE: "ITW_PROXIMITY_CLAIMS_DISCLOSURE",
  SEND_DOCUMENTS_RESPONSE: "ITW_PROXIMITY_SEND_DOCUMENTS_RESPONSE",
  FAILURE: "ITW_PROXIMITY_FAILURE"
} as const;
