export const ITW_PROXIMITY_ROUTES = {
  MAIN: "ITW_PROXIMITY_MAIN",
  QR_CODE: "ITW_PROXIMITY_QR_CODE",
  BLUETOOTH_PERMISSIONS: "ITW_PROXIMITY_BLUETOOTH_PERMISSIONS",
  BLUETOOTH_ACTIVATION: "ITW_PROXIMITY_BLUETOOTH_ACTIVATION",
  NFC_ACTIVATION: "ITW_PROXIMITY_NFC_ACTIVATION",
  CLAIMS_DISCLOSURE: "ITW_PROXIMITY_CLAIMS_DISCLOSURE",
  SEND_DOCUMENTS_RESPONSE: "ITW_PROXIMITY_SEND_DOCUMENTS_RESPONSE",
  FAILURE: "ITW_PROXIMITY_FAILURE"
} as const;
