import DESIGN_SYSTEM_ROUTES from "./routes";

export type DesignSystemParamsList = {
  [DESIGN_SYSTEM_ROUTES.MAIN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.COLOR.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.TYPOGRAPHY.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LAYOUT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.ICONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.PICTOGRAMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.HAPTIC_FEEDBACK.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LOADERS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LOGOS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BUTTONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BADGE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.SELECTION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ADVICE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.COLLAPSIBLE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ALERT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.STEPPER.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.OTP_INPUT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.TEXT_FIELDS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.LIST_ITEMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.MODULES.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.TOASTS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BOTTOM_SHEET.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.TAB_NAVIGATION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.WALLET.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.IO_MARKDOWN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.HEADERS.FIRST_LEVEL.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.HEADERS.SECOND_LEVEL.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.HEADERS.SECOND_LEVEL_SECTION_TITLE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.OPERATION_RESULT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.OPERATION_RESULT_ANIMATED.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.IOSCROLLVIEW.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.IOSCROLLVIEW_WO_ACTIONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.IOSCROLLVIEW_LARGEHEADER.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.IOSCROLLVIEW_CENTRED_CONTENT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.IOSCROLLVIEW_WITH_LIST_ITEMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.IOLISTVIEW_LARGE_HEADER.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.FORSCESCROLLDOWNVIEW_ACTIONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.FORSCESCROLLDOWNVIEW_CUSTOM_SLOT
    .route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.FORSCESCROLLDOWNVIEW_TITLE_TRANSITION
    .route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.BONUS_CARD_SCREEN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.LOADING_SCREEN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.LOADING_SCREEN_EXTENDED_PROPS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.NUMBERPAD.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.CARDS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.SAFE_AREA.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.SAFE_AREA_CENTERED.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.EDGE_TO_EDGE_AREA.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FULL_SCREEN_MODAL.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FOOTER_ACTIONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FOOTER_ACTIONS_STICKY.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FOOTER_ACTIONS_NOT_FIXED.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FOOTER_ACTIONS_INLINE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FOOTER_ACTIONS_INLINE_NOT_FIXED.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.SCREEN_END_MARGIN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.EXPERIMENTAL_LAB.ANIMATED_PICTOGRAMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.EXPERIMENTAL_LAB.DYNAMIC_BACKGROUND.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.EXPERIMENTAL_LAB.DYNAMIC_CARD_ROTATION
    .route]: undefined;
  [DESIGN_SYSTEM_ROUTES.EXPERIMENTAL_LAB.IRIDESCENT_TRUSTMARK.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.EXPERIMENTAL_LAB.ITW_BRAND_EXPLORATION
    .route]: undefined;
};
