import DESIGN_SYSTEM_ROUTES from "./routes";

export type DesignSystemParamsList = {
  [DESIGN_SYSTEM_ROUTES.MAIN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.COLOR.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.TYPOGRAPHY.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LAYOUT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.ICONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.PICTOGRAMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.HAPTIC_FEEDBACK.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LOADERS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LOGOS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BUTTONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BADGE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.SELECTION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ADVICE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ACCORDION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ALERT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.TEXT_FIELDS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.LIST_ITEMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.MODULES.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.TOASTS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BOTTOM_SHEET.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.TAB_NAVIGATION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.WALLET.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.HEADERS.FIRST_LEVEL.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.HEADERS.SECOND_LEVEL.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.HEADERS.SECOND_LEVEL_SECTION_TITLE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.GRADIENT_SCROLL.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.OPERATION_RESULT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.WIZARD_SCREEN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.BONUS_CARD_SCREEN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.SCREENS.NUMBERPAD.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.CARDS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.SAFE_AREA.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.SAFE_AREA_CENTERED.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.EDGE_TO_EDGE_AREA.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.STICKY_MESSAGE_CTAS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.LEGACY.PICTOGRAMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.LEGACY.ILLUSTRATIONS.route]: undefined;
};

export type DesignSystemModalParamsList = {
  [DESIGN_SYSTEM_ROUTES.MAIN.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.DEBUG.FULL_SCREEN_MODAL.route]: undefined;
};
