const WALLET_ONBOARDING_BPAY_ROUTES = {
  MAIN: "WALLET_ONBOARDING_BPAY_MAIN",

  START: "WALLET_ONBOARDING_BPAY_START",
  CHOOSE_BANK: "WALLET_ONBOARDING_BPAY_CHOOSE_BANK_SCREEN",
  SEARCH_AVAILABLE_USER_ACCOUNT:
    "WALLET_ONBOARDING_BPAY_SEARCH_AVAILABLE_USER_ACCOUNT",

  ADD_BPAY: "WALLET_ONBOARDING_BPAY_ADD",
  ACTIVATE_BPD_NEW: "WALLET_ONBOARDING_BPAY_ACTIVATE_BPD_NEW"
};

export default WALLET_ONBOARDING_BPAY_ROUTES;
