const WALLET_ONBOARDING_BANCOMATPAY_ROUTES = {
  MAIN: "WALLET_ONBOARDING_BANCOMATPAY_MAIN",

  START: "WALLET_ONBOARDING_BANCOMATPAY_START",
  CHOOSE_BANK: "WALLET_ONBOARDING_BANCOMATPAY_CHOOSE_BANK_SCREEN",
  SEARCH_AVAILABLE_USER_ACCOUNT:
    "WALLET_ONBOARDING_BANCOMATPAY_SEARCH_AVAILABLE_USER_ACCOUNT",

  ADD_BANCOMATPAY: "WALLET_ONBOARDING_BANCOMATPAY_ADD",
  ACTIVATE_BPD_NEW: "WALLET_ONBOARDING_BANCOMATPAY_ACTIVATE_BPD_NEW"
};

export default WALLET_ONBOARDING_BANCOMATPAY_ROUTES;
