export const mockIDPayClient = {
  getInitiativeData: jest.fn(),
  getInitiativeBeneficiaryDetail: jest.fn(),
  checkPrerequisites: jest.fn(),
  consentOnboarding: jest.fn(),
  onboardingCitizen: jest.fn(),
  onboardingStatus: jest.fn(),
  deleteInstrument: jest.fn(),
  enrollIban: jest.fn(),
  enrollInstrument: jest.fn(),
  getIban: jest.fn(),
  getIbanList: jest.fn(),
  getInstrumentList: jest.fn(),
  getTimeline: jest.fn(),
  getTimelineDetail: jest.fn(),
  getWallet: jest.fn(),
  getWalletDetail: jest.fn(),
  getWalletStatus: jest.fn(),
  unsubscribe: jest.fn(),
  getInitiativesWithInstrument: jest.fn(),
  putAuthPayment: jest.fn(),
  putPreAuthPayment: jest.fn()
};
