const PN_ROUTES = {
  MAIN: "PN_MAIN",
  MESSAGE_DETAILS: "PN_MESSAGE_DETAILS",
  MESSAGE_ATTACHMENT: "PN_MESSAGE_ATTACHMENT",
  CANCELLED_MESSAGE_PAID_PAYMENT: "PN_CANCELLED_MESSAGE_PAID_PAYMENT"
} as const;

export default PN_ROUTES;
