const PN_ROUTES = {
  MAIN: "PN_ROUTES_MAIN",
  MESSAGE_DETAILS: "PN_ROUTES_MESSAGE_DETAILS",
  MESSAGE_ATTACHMENT: "PN_ROUTES_MESSAGE_ATTACHMENT",
  CANCELLED_MESSAGE_PAID_PAYMENT: "PN_CANCELLED_MESSAGE_PAID_PAYMENT",
  ACTIVATION_BANNER_FLOW: "PN_ACTIVATION_BANNER_FLOW",
  ENGAGEMENT_SCREEN: "SEND_ENGAGEMENT_SCREEN"
} as const;

export default PN_ROUTES;
