export const CIE_PLAYGROUNDS_ROUTES = {
  MAIN: "CIE_PLAYGROUNDS_MAIN",
  ATTRIBUTES: "CIE_PLAYGROUNDS_ATTRIBUTES",
  INTERNAL_AUTH: "CIE_PLAYGROUNDS_INTERNAL_AUTH",
  MRTD: "CIE_PLAYGROUNDS_MRTD",
  INTERNAL_AUTH_MRTD: "CIE_PLAYGROUNDS_INTERNAL_AUTH_MRTD",
  CERTIFICATE_READING: "CIE_PLAYGROUNDS_CERTIFICATE_READING",
  AUTHENTICATION: "CIE_PLAYGROUNDS_AUTHENTICATION",
  RESULT: "CIE_PLAYGROUNDS_RESULT"
} as const;
