import { BonusInformationScreenNavigationParams } from "../screens/BonusInformationScreen";
import BONUSVACANZE_ROUTES from "./routes";

export type BonusVacanzeParamsList = {
  [BONUSVACANZE_ROUTES.BONUS_AVAILABLE_LIST]: undefined;
  [BONUSVACANZE_ROUTES.BONUS_REQUEST_INFORMATION]: BonusInformationScreenNavigationParams;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.CHECK_LOADING]: undefined;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.ISEE_NOT_AVAILABLE]: undefined;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.ISEE_NOT_ELIGIBLE]: undefined;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.ELIGIBLE]: undefined;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.TIMEOUT]: undefined;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.PENDING]: undefined;
  [BONUSVACANZE_ROUTES.ELIGIBILITY.UNDERAGE]: undefined;
  [BONUSVACANZE_ROUTES.ACTIVATION.LOADING]: undefined;
  [BONUSVACANZE_ROUTES.ACTIVATION.TIMEOUT]: undefined;
  [BONUSVACANZE_ROUTES.ACTIVATION.EXISTS]: undefined;
  [BONUSVACANZE_ROUTES.ACTIVATION.ELIGIBILITY_EXPIRED]: undefined;
  [BONUSVACANZE_ROUTES.ACTIVATION.COMPLETED]: undefined;
  [BONUSVACANZE_ROUTES.BONUS_CTA_ELIGILITY_START]: undefined;
};
