export enum ITW_IDENTIFICATION_SCREENVIEW_EVENTS {
  ITW_ID_METHOD = "ITW_ID_METHOD",
  ITW_SPID_IDP_SELECTION = "ITW_SPID_IDP_SELECTION",
  ITW_CIE_PIN_ENTER = "ITW_CIE_PIN_ENTER",
  ITW_CIE_NFC_ACTIVATION = "ITW_CIE_NFC_ACTIVATION",
  ITW_CIE_CARD_READING = "ITW_CIE_CARD_READING",
  ITW_CARD_READING_SUCCESS = "ITW_CARD_READING_SUCCESS",
  ITW_PIN_INFO_BOTTOMSHEET = "ITW_PIN_INFO_BOTTOMSHEET",
  ITW_CIE_INFO_BOTTOMSHEET = "ITW_CIE_INFO_BOTTOMSHEET",
  ITW_CIE_PIN_TUTORIAL_CIE = "ITW_CIE_PIN_TUTORIAL_CIE",
  ITW_CIE_PIN_TUTORIAL_PIN = "ITW_CIE_PIN_TUTORIAL_PIN",
  ITW_USER_WITHOUT_L3_BOTTOMSHEET = "ITW_USER_WITHOUT_L3_BOTTOMSHEET"
}

export enum ITW_IDENTIFICATION_ACTIONS_EVENTS {
  ITW_SPID_IDP_SELECTED = "ITW_SPID_IDP_SELECTED",
  ITW_CIE_PIN_INFO = "ITW_CIE_PIN_INFO",
  ITW_CIE_PIN_FORGOTTEN = "ITW_CIE_PIN_FORGOTTEN",
  ITW_CIE_PUK_FORGOTTEN = "ITW_CIE_PUK_FORGOTTEN",
  ITW_CIE_NFC_GO_TO_SETTINGS = "ITW_CIE_NFC_GO_TO_SETTINGS"
}

export enum ITW_IDENTIFICATION_ERRORS_EVENTS {
  ITW_CIE_CARD_READING_ERROR = "ITW_CIE_CARD_READING_ERROR",
  ITW_CIE_PIN_ERROR = "ITW_CIE_PIN_ERROR",
  ITW_CIE_PIN_SECOND_ERROR = "ITW_CIE_PIN_SECOND_ERROR",
  ITW_CIE_PIN_LAST_ERROR = "ITW_CIE_PIN_LAST_ERROR",
  ITW_CIE_CARD_READING_CLOSE = "ITW_CIE_CARD_READING_CLOSE",
  ITW_CIE_CARD_VERIFY_FAILURE = "ITW_CIE_CARD_VERIFY_FAILURE",
  ITW_CIE_CARD_READING_FAILURE = "ITW_CIE_CARD_READING_FAILURE",
  ITW_CIE_CARD_READING_UNEXPECTED_FAILURE = "ITW_CIE_CARD_READING_UNEXPECTED_FAILURE",
  ITW_USER_WITHOUT_L3_REQUIREMENTS = "ITW_USER_WITHOUT_L3_REQUIREMENTS"
}
