export enum ITW_PRESENTATION_DETAILS_SCREENVIEW_EVENTS {
  ITW_CREDENTIAL_DETAIL = "ITW_CREDENTIAL_DETAIL",
  "ITW_CREDENTIAL_FAC-SIMILE" = "ITW_CREDENTIAL_FAC-SIMILE",
  ITW_CREDENTIAL_BOTTOMSHEET = "ITW_CREDENTIAL_BOTTOMSHEET"
}

export enum ITW_PRESENTATION_DETAILS_ACTIONS_EVENTS {
  ITW_CREDENTIAL_DELETE = "ITW_CREDENTIAL_DELETE",
  ITW_CREDENTIAL_BOTTOMSHEET_ACTION = "ITW_CREDENTIAL_BOTTOMSHEET_ACTION",
  ITW_CREDENTIAL_SHOW_BACK = "ITW_CREDENTIAL_SHOW_BACK",
  ITW_CREDENTIAL_SUPPORT = "ITW_CREDENTIAL_SUPPORT",
  "ITW_CREDENTIAL_SHOW_FAC-SIMILE" = "ITW_CREDENTIAL_SHOW_FAC-SIMILE",
  ITW_CREDENTIAL_SHOW_TRUSTMARK = "ITW_CREDENTIAL_SHOW_TRUSTMARK",
  ITW_CREDENTIAL_CARD_MODAL = "ITW_CREDENTIAL_CARD_MODAL",
  ITW_CREDENTIAL_TAP_BANNER = "ITW_CREDENTIAL_TAP_BANNER",
  ITW_REISSUING_EID_MANDATORY = "ITW_REISSUING_EID_MANDATORY"
}
