export enum ITW_PRESENTATION_DETAILS_SCREENVIEW_EVENTS {
  ITW_CREDENTIAL_DETAIL = "ITW_CREDENTIAL_DETAIL",
  "ITW_CREDENTIAL_FAC-SIMILE" = "ITW_CREDENTIAL_FAC-SIMILE",
  ITW_CREDENTIAL_BOTTOMSHEET = "ITW_CREDENTIAL_BOTTOMSHEET"
}

export enum ITW_PRESENTATION_DETAILS_ACTIONS_EVENTS {
  ITW_CREDENTIAL_DELETE = "ITW_CREDENTIAL_DELETE"
}
