export const ITW_ROUTES = {
  MAIN: "ITW_MAIN",
  DISCOVERY: {
    INFO: "ITW_DISCOVERY_INFO",
    FEATURES_INFO: "ITW_DISCOVERY_FEATURES_INFO"
  } as const,
  ISSUING: {
    CIE: {
      EXPIRED_SCREEN: "ITW_ISSUING_CIE_EXPIRED_SCREEN",
      PIN_SCREEN: "ITW_ISSUING_CIE_PIN_SCREEN",
      CARD_READER_SCREEN: "ITW_ISSUING_CIE_CARD_READER_SCREEN",
      CONSENT_DATA_USAGE: "ITW_ISSUING_CIE_CONSENT_DATA_USAGE",
      WRONG_PIN_SCREEN: "ITW_ISSUING_CIE_WRONG_PIN_SCREEN",
      PIN_TEMP_LOCKED_SCREEN: "ITW_ISSUING_CIE_PIN_TEMP_LOCKED_SCREEN"
    } as const,
    PID_AUTH_INFO: "ITW_ISSUING_PID_AUTH_INFO",
    PID_REQUEST: "ITW_ISSUING_PID_REQUEST",
    PID_PREVIEW: "ITW_ISSUING_PID_PREVIEW",
    PID_ADDING: "ITW_ISSUING_PID_ADDING"
  } as const,
  PRESENTATION: {
    PID_DETAILS: "ITW_PRESENTATION_PID_DETAILS",
    CROSS_DEVICE: {
      CHECKS: "ITW_PRESENTATION_CROSS_DEVICE_CHECKS",
      DATA: "ITW_PRESENTATION_CROSS_DEVICE_DATA",
      INIT: "ITW_PRESENTATION_CROSS_DEVICE_INIT",
      RESULT: "ITW_PRESETATION_CROSS_DEVICE_RESULT",
      RESULT_NEW: "ITW_PRESETATION_CROSS_DEVICE_RESULT_NEW"
    } as const
  },
  CREDENTIALS: {
    CATALOG: "ITW_CREDENTIALS_CATALOG",
    ADD_CHECKS: "ITW_CREDENTIALS_ADD_CHECKS",
    ISSUING_INFO: "ITW_CREDENTIALS_ISSUING_INFO",
    PREVIEW: "ITW_CREDENTIALS_PREVIEW"
  } as const,
  GENERIC: {
    NOT_AVAILABLE: "ITW_GENERIC_NOT_AVAILABLE"
  }
} as const;
