export const ITW_ROUTES = {
  MAIN: "ITW_MAIN",
  ACTIVATION: {
    DETAILS: "ITW_ACTIVATION_DETAILS",
    INFO: "ITW_ACTIVATION_INFO",
    PID_PREVIEW: "ITW_ACTIVATION_PID_PREVIEW"
  } as const
} as const;
