const BONUSVACANZE_ROUTES = {
  MAIN: "MAIN",

  BONUS_AVAILABLE_LIST: "BONUS_AVAILABLE_LIST",
  BONUS_REQUEST_INFORMATION: "BONUS_REQUEST_INFORMATION",
  BONUS_TOS_SCREEN: "BONUS_TOS_SCREEN",
  BONUS_ACTIVE_DETAIL_SCREEN: "BONUS_ACTIVE_DETAIL_SCREEN",

  // Grouping the "Bonus Eligibility Verification" sub-phase
  ELIGIBILITY: {
    CHECK_LOADING: "BONUS_ELIGIBILITY_CHECK_LOADING",
    ISEE_NOT_AVAILABLE: "BONUS_ELIGIBILITY_ISEE_NOT_AVAILABLE",
    ISEE_NOT_ELIGIBLE: "BONUS_ELIGIBILITY_ISEE_NOT_ELIGIBLE",
    TIMEOUT: "BONUS_ELIGIBILITY_TIMEOUT",
    ELIGIBLE: "BONUS_ELIGIBILITY_ELIGIBLE"
  },
  // Grouping the "Bonus Activation" sub-phase
  ACTIVATION: {
    LOADING: "BONUS_ACTIVATION_LOADING",
    TIMEOUT: "BONUS_ACTIVATION_TIMEOUT",
    ELIGIBILITY_EXPIRED: "BONUS_ACTIVATION_ELIGIBILITY_EXPIRED",
    EXISTS: "BONUS_ACTIVATION_EXISTS",
    COMPLETED: "BONUS_ACTIVATION_COMPLETED"
  }
};

export default BONUSVACANZE_ROUTES;
