const BONUSVACANZE_ROUTES = {
  MAIN: "MAIN",

  // Grouping the "Bonus Eligibility Verification" sub-phase
  ELIGIBILITY: {
    CHECK_LOADING: "BONUS_ELIGIBILITY_CHECK_LOADING",
    ISEE_NOT_AVAILABLE: "BONUS_ELIGIBILITY_ISEE_NOT_AVAILABLE",
    ISEE_NOT_ELIGIBLE: "BONUS_ELIGIBILITY_ISEE_NOT_ELIGIBLE",
    ACTIVATE_BONUS: "BONUS_ELIGIBILITY_ACTIVATE",
    TIMEOUT: "BONUS_ELIGIBILITY_TIMEOUT",
    ACTIVATION_LOADING: "BONUS_ELIGIBILITY_ACTIVATION_LOADING"
  }
};

export default BONUSVACANZE_ROUTES;
