import { RequestHeaderProducer } from "@pagopa/ts-commons/lib/requests";

/**
 * Produce a base header for the BPD API requests
 */
export const bpdHeadersProducers = <
  P extends {
    readonly Authorization: string;
  }
>() =>
  ((p: P) => ({
    // since these headers are not correctly autogenerated we have to access them as an anonymous object
    Authorization: `Bearer ${(p as any).Bearer}`
  })) as RequestHeaderProducer<P, "Authorization">;
