const EUCOVIDCERT_ROUTES = {
  MAIN: "EUCOVIDCERT_ROUTES_MAIN",
  CERTIFICATE: "EUCOVIDCERT_CERTIFICATE",
  QRCODE: "EUCOVIDCERT_QRCODE",
  MARKDOWN_DETAILS: "EUCOVIDCERT_MARKDOWN_DETAILS"
};

export default EUCOVIDCERT_ROUTES;
