export enum ITW_SCREENVIEW_EVENTS {
  BANNER = "BANNER",
  ITW_INTRO = "ITW_INTRO",
  WALLET = "WALLET",
  WALLET_ADD_LIST_ITEM = "WALLET_ADD_LIST_ITEM",
  ITW_DATA_SHARE = "ITW_DATA_SHARE",
  ITW_OPERATION_BLOCK = "ITW_OPERATION_BLOCK",
  ITW_BANNER = "ITW_BANNER",
  SURVEY_REQUEST = "SURVEY_REQUEST",
  ITW_SETTINGS = "ITW_SETTINGS"
}

export enum ITW_ACTIONS_EVENTS {
  TAP_BANNER = "TAP_BANNER",
  CLOSE_BANNER = "CLOSE_BANNER",
  ITW_TOS = "ITW_TOS",
  ITW_DATA_SHARE_ACCEPTED = "ITW_DATA_SHARE_ACCEPTED",
  WALLET_ADD_START = "WALLET_ADD_START",
  ITW_KO_STATE_ACTION_SELECTED = "ITW_KO_STATE_ACTION_SELECTED",
  ITW_ID_METHOD_SELECTED = "ITW_ID_METHOD_SELECTED",
  WALLET_ADD = "WALLET_ADD",
  WALLET_CATEGORY_FILTER = "WALLET_CATEGORY_FILTER",
  ITW_CREDENTIAL_SHOW_ISSUER = "ITW_CREDENTIAL_SHOW_ISSUER",
  ITW_CREDENTIAL_SHOW_AUTH_SOURCE = "ITW_CREDENTIAL_SHOW_AUTH_SOURCE",
  ITW_START_ACTIVATION = "ITW_START_ACTIVATION",
  ITW_START_DEACTIVATION = "ITW_START_DEACTIVATION",
  ITW_CREDENTIAL_COPY_LIST_ITEM = "ITW_CREDENTIAL_COPY_LIST_ITEM",
  ITW_OPERATION_BLOCK_ACTION = "ITW_OPERATION_BLOCK_ACTION",
  ITW_TAP_BANNER = "ITW_TAP_BANNER",
  ITW_CLOSE_BANNER = "ITW_CLOSE_BANNER",
  ITW_CREDENTIAL_START_REISSUING = "ITW_CREDENTIAL_START_REISSUING",
  ITW_CREDENTIAL_QUALIFICATION_DETAIL = "ITW_CREDENTIAL_QUALIFICATION_DETAIL",
  SURVEY_REQUEST_ACCEPTED = "SURVEY_REQUEST_ACCEPTED",
  SURVEY_REQUEST_DECLINED = "SURVEY_REQUEST_DECLINED"
}

export enum ITW_ERRORS_EVENTS {
  ITW_ADD_CREDENTIAL_TIMEOUT = "ITW_ADD_CREDENTIAL_TIMEOUT",
  ITW_STATUS_CREDENTIAL_ATTESTATION_FAILURE = "ITW_STATUS_CREDENTIAL_ATTESTATION_FAILURE",
  ITW_TRUSTMARK_RENEW_FAILURE = "ITW_TRUSTMARK_RENEW_FAILURE"
}

export enum ITW_TECH_EVENTS {
  ITW_ID_REQUEST = "ITW_ID_REQUEST",
  ITW_ID_AUTHENTICATION_COMPLETED = "ITW_ID_AUTHENTICATION_COMPLETED",
  ITW_ID_VERIFIED_DOCUMENT = "ITW_ID_VERIFIED_DOCUMENT"
}

export enum ITW_CONFIRM_EVENTS {
  ITW_UX_SUCCESS = "ITW_UX_SUCCESS",
  ITW_DEACTIVATED = "ITW_DEACTIVATED"
}
