export enum ITW_SCREENVIEW_EVENTS {
  BANNER = "BANNER",
  ITW_INTRO = "ITW_INTRO",
  ITW_ID_METHOD = "ITW_ID_METHOD",
  ITW_SPID_IDP_SELECTION = "ITW_SPID_IDP_SELECTION",
  ITW_CIE_PIN_ENTER = "ITW_CIE_PIN_ENTER",
  ITW_CIE_NFC_ACTIVATION = "ITW_CIE_NFC_ACTIVATION",
  ITW_CIE_CARD_READING = "ITW_CIE_CARD_READING",
  ITW_CARD_READING_SUCCESS = "ITW_CARD_READING_SUCCESS"
}

export enum ITW_ACTIONS_EVENTS {
  CLOSE_BANNER = "CLOSE_BANNER",
  TAP_BANNER = "TAP_BANNER",
  ITW_TOS = "ITW_TOS",
  ITW_ID_START = "ITW_ID_START",
  ITW_ID_METHOD_SELECTED = "ITW_ID_METHOD_SELECTED",
  ITW_SPID_IDP_SELECTED = "ITW_SPID_IDP_SELECTED",
  ITW_CIE_PIN_INFO = "ITW_CIE_PIN_INFO",
  ITW_CIE_PIN_FORGOTTEN = "ITW_CIE_PIN_FORGOTTEN",
  ITW_CIE_PUK_FORGOTTEN = "ITW_CIE_PUK_FORGOTTEN",
  ITW_CIE_NFC_GO_TO_SETTINGS = "ITW_CIE_NFC_GO_TO_SETTINGS",
  ITW_CIE_RETRY_PIN = "ITW_CIE_RETRY_PIN"
}

export enum ITW_ERRORS_EVENTS {
  ITW_DEVICE_NOT_SUPPORTED = "ITW_DEVICE_NOT_SUPPORTED",
  ITW_CIE_CARD_READING_ERROR = "ITW_CIE_CARD_READING_ERROR",
  ITW_CIE_PIN_ERROR = "ITW_CIE_PIN_ERROR",
  ITW_CIE_PIN_SECOND_ERROR = "ITW_CIE_PIN_SECOND_ERROR",
  ITW_CIE_PIN_LAST_ERROR = "ITW_CIE_PIN_LAST_ERROR",
  ITW_CIE_CARD_VERIFY_FAILURE = "ITW_CIE_CARD_VERIFY_FAILURE",
  ITW_CIE_CARD_READING_FAILURE = "ITW_CIE_CARD_READING_FAILURE"
}
