export const WalletPaymentRoutes = {
  WALLET_PAYMENT_MAIN: "_PAYMENT_MAIN",
  WALLET_PAYMENT_BARCODE_SCAN: "WALLET_PAYMENT_BARCODE_SCAN",
  WALLET_PAYMENT_BARCODE_CHOICE: "WALLET_PAYMENT_BARCODE_CHOICE",
  WALLET_PAYMENT_CHECKOUT_METHOD_SELECTION:
    "WALLET_PAYMENT_CHECKOUT_METHOD_SELECTION"
} as const;
