export const WalletPaymentRoutes = {
  WALLET_PAYMENT_MAIN: "WALLET_PAYMENT_MAIN",
  WALLET_PAYMENT_BARCODE_SCAN: "WALLET_PAYMENT_BARCODE_SCAN",
  WALLET_PAYMENT_BARCODE_CHOICE: "WALLET_PAYMENT_BARCODE_CHOICE",
  WALLET_PAYMENT_INPUT_NOTICE_NUMBER: "WALLET_PAYMENT_INPUT_NOTICE_NUMBER",
  WALLET_PAYMENT_INPUT_FISCAL_CODE: "WALLET_PAYMENT_INPUT_FISCAL_CODE"
} as const;
