export const WalletPaymentRoutes = {
  WALLET_PAYMENT_MAIN: "WALLET_PAYMENT_MAIN",
  WALLET_PAYMENT_BARCODE_SCAN: "WALLET_PAYMENT_BARCODE_SCAN",
  WALLET_PAYMENT_BARCODE_CHOICE: "WALLET_PAYMENT_BARCODE_CHOICE"
} as const;
