export enum States {
  AWAITING_CODE_INPUT = "AWAITING_CODE_INPUT",
  LOADING_TRANSACTION_DATA = "LOADING_TRANSACTION_DATA",
  DISPLAYING_TRANSACTION_DATA = "DISPLAYING_TRANSACTION_DATA",
  AUTHORIZING = "AUTHORIZING",
  AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS",
  AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE"
}
