import { ITW_PLAYGROUND_ROUTES } from "../playgrounds/navigation/routes";
import { ITW_PROXIMITY_ROUTES } from "../presentation/proximity/navigation/routes";

export const ITW_ROUTES = {
  MAIN: "ITW_MAIN" as const,
  OFFLINE: {
    WALLET: "ITW_OFFLINE_WALLET"
  } as const,
  ONBOARDING: "ITW_CARD_ONBOARDING" as const,
  DISCOVERY: {
    INFO: "ITW_DISCOVERY_INFO",
    IPZS_PRIVACY: "ITW_IPZS_PRIVACY",
    ALREADY_ACTIVE_SCREEN: "ITW_ALREADY_ACTIVE_SCREEN"
  } as const,
  IDENTIFICATION: {
    MODE_SELECTION: "ITW_IDENTIFICATION_MODE_SELECTION",
    IDP_SELECTION: "ITW_IDENTIFICATION_IDP_SELECTION",
    CIE_WARNING: "ITW_IDENTIFICATION_CIE_WARNING",
    SPID: {
      LOGIN: "ITW_IDENTIFICATION_SPID_LOGIN"
    },
    CIE_ID: {
      LOGIN: "ITW_IDENTIFICATION_CIEID_LOGIN"
    },
    CIE: {
      ACTIVATE_NFC: "ITW_IDENTIFICATION_CIE_ACTIVATE_NFC",
      PREPARATION: {
        CARD_SCREEN: "ITW_IDENTIFICATION_CIE_CARD_PREPARATION_SCREEN",
        NFC_SCREEN: "ITW_IDENTIFICATION_CIE_NFC_PREPARATION_SCREEN",
        PIN_SCREEN: "ITW_IDENTIFICATION_CIE_PIN_PREPARATION_SCREEN",
        CAN_SCREEN: "ITW_IDENTIFICATION_CIE_CAN_PREPARATION_SCREEN"
      },
      PIN_SCREEN: "ITW_IDENTIFICATION_CIE_PIN_SCREEN",
      CAN_SCREEN: "ITW_IDENTIFICATION_CIE_CAN_SCREEN",
      AUTH_SCREEN: "ITW_IDENTIFICATION_CIE_AUTH_SCREEN",
      INTERNAL_AUTH_MRTD_SCREEN:
        "ITW_IDENTIFICATION_CIE_INTERNAL_AUTH_MRTD_SCREEN"
    }
  } as const,
  ISSUANCE: {
    EID_PREVIEW: "ITW_ISSUANCE_EID_PREVIEW",
    EID_RESULT: "ITW_ISSUANCE_EID_RESULT",
    EID_FAILURE: "ITW_ISSUANCE_EID_FAILURE",
    CREDENTIAL_INTRODUCTION: "ITW_ISSUANCE_CREDENTIAL_INTRODUCTION",
    CREDENTIAL_TRUST_ISSUER: "ITW_ISSUANCE_CREDENTIAL_TRUST_ISSUER",
    CREDENTIAL_PREVIEW: "ITW_ISSUANCE_CREDENTIAL_PREVIEW",
    CREDENTIAL_FAILURE: "ITW_ISSUANCE_CREDENTIAL_FAILURE",
    UPCOMING_CREDENTIAL: "ITW_ISSUANCE_UPCOMING_CREDENTIAL",
    UPDATE_CREDENTIALS: "ITW_ISSUANCE_UPDATE_CREDENTIALS"
  } as const,
  PRESENTATION: {
    CREDENTIAL_DETAIL: "ITW_PRESENTATION_CREDENTIAL_DETAIL",
    CREDENTIAL_ATTACHMENT: "ITW_PRESENTATION_CREDENTIAL_ATTACHMENT",
    CREDENTIAL_TRUSTMARK: "ITW_PRESENTATION_CREDENTIAL_TRUSTMARK",
    CREDENTIAL_CARD_MODAL: "ITW_PRESENTATION_CREDENTIAL_CARD_MODAL",
    CREDENTIAL_FISCAL_CODE_MODAL:
      "ITW_PRESENTATION_CREDENTIAL_FISCAL_CODE_MODAL",
    EID_VERIFICATION_EXPIRED: "ITW_PRESENTATION_EID_VERIFICATION_EXPIRED",
    PID_DETAIL: "ITW_PRESENTATION_PID_DETAIL"
  } as const,
  PROXIMITY: ITW_PROXIMITY_ROUTES,
  PLAYGROUNDS: ITW_PLAYGROUND_ROUTES,
  SETTINGS: "ITW_SETTINGS" as const,
  IDENTITY_NOT_MATCHING_SCREEN: "ITW_IDENTITY_NOT_MATCHING_SCREEN" as const,
  WALLET_REVOCATION_SCREEN: "ITW_WALLET_REVOCATION_SCREEN" as const,
  LANDING: {
    CREDENTIAL_ASYNC_FLOW_CONTINUATION:
      "ITW_LANDING_SCREEN_CREDENTIAL_ASYNC_FLOW_CONTINUATION",
    EID_REISSUANCE: "ITW_LANDING_SCREEN_EID_REISSUANCE"
  } as const
};
