export const ITW_ROUTES = {
  MAIN: "ITW_MAIN" as const,
  DISCOVERY: {
    INFO: "ITW_DISCOVERY_INFO"
  } as const,
  IDENTIFICATION: {
    MODE_SELECTION: "ITW_IDENTIFICATION_MODE_SELECTION",
    NFC_INSTRUCTIONS: "ITW_IDENTIFICATION_NFC_INSTRUCTIONS",
    IDP_SELECTION: "ITW_IDENTIFICATION_IDP_SELECTION"
  } as const,
  ISSUANCE: {
    EID_PREVIEW: "ITW_ISSUANCE_EID_PREVIEW",
    CREDENTIAL_AUTH: "ITW_ISSUANCE_CREDENTIAL_AUTH",
    CREDENTIAL_PREVIEW: "ITW_ISSUANCE_CREDENTIAL_PREVIEW",
    RESULT: "ITW_ISSUANCE_RESULT",
    EID_CIE: {
      PIN_SCREEN: "ITW_ISSUANCE_EID_CIE_PIN_SCREEN",
      CARD_READER_SCREEN: "ITW_ISSUANCE_EID_CIE_CARD_READER_SCREEN",
      CONSENT_DATA_USAGE: "ITW_ISSUANCE_EID_CIE_CONSENT_DATA_USAGE",
      WRONG_PIN: "ITW_ISSUANCE_EID_CIE_WRONG_PIN",
      WRONG_CARD: "ITW_ISSUANCE_EID_CIE_WRONG_CARD"
    }
  } as const,
  PRESENTATION: {
    EID_DETAIL: "ITW_PRESENTATION_EID_DETAIL"
  } as const
};
