name: Actions to notify E2E tests failure through Slack message
description: 'This action collects the steps to setup python env and run job'
runs:
  using: "composite"
  steps:
    - name: setup python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c #v5.0.0
      with:
        python-version: '3.11.7'
    - name: install pipenv
      run: pip install pipenv
      shell: bash
    - name: report E2E tests failure
      run: |
        cd scripts/e2e_message
        pipenv install
        pipenv run python3 e2e_notifier.py
      env: 
        BUILD_ID: ${{ github.run_id }}
      shell: bash