const ROUTES = {
  // Ingress
  INGRESS: 'INGRESS',

  // Authentication
  AUTHENTICATION: 'AUTHENTICATION',
  AUTHENTICATION_LANDING: 'AUTHENTICATION/LANDING',
  AUTHENTICATION_LOGIN: 'AUTHENTICATION/LOGIN',

  // Main
  MAIN: 'MAIN',
  MAIN_MESSAGES: 'MAIN_MESSAGES',
  MAIN_PROFILE: 'MAIN_PROFILE'
}

export default ROUTES
