const ROUTES = {
  // Ingress
  INGRESS: 'INGRESS',

  // Authentication
  AUTHENTICATION: 'AUTHENTICATION',
  AUTHENTICATION_LANDING: 'AUTHENTICATION_LANDING',
  AUTHENTICATION_IPD_SELECTION: 'AUTHENTICATION_IPD_SELECTION',
  AUTHENTICATION_LOGIN: 'AUTHENTICATION_LOGIN',

  // Main
  MAIN: 'MAIN',
  MAIN_MESSAGES: 'MAIN_MESSAGES',
  MAIN_PROFILE: 'MAIN_PROFILE'
}

export default ROUTES
