const ROUTES = {
  // Ingress
  INGRESS: 'INGRESS',

  // Authentication
  AUTHENTICATION: 'AUTHENTICATION',
  AUTHENTICATION_LANDING: 'AUTHENTICATION_LANDING',
  AUTHENTICATION_IDP_SELECTION: 'AUTHENTICATION_IPD_SELECTION',
  AUTHENTICATION_IDP_LOGIN: 'AUTHENTICATION_IPD_LOGIN',
  AUTHENTICATION_LOGIN: 'AUTHENTICATION_LOGIN',
  AUTHENTICATION_SPID_INFORMATION_REQUEST:
    'AUTHENTICATION_SPID_INFORMATION_REQUEST',

  // Onboarding
  ONBOARDING: 'ONBOARDING',
  ONBOARDING_TOS: 'ONBOARDING_TOS',
  ONBOARDING_PIN: 'ONBOARDING_PIN',

  // Portfolio
  PORTFOLIO_HOME: 'PORTFOLIO_HOME',
  PORTFOLIO_OPERATION_DETAILS: 'PORTFOLIO_OPERATION_DETAILS',
  PORTFOLIO_CREDITCARDS: 'PORTFOLIO_CREDITCARDS',
  PORTFOLIO_CARDS_OPERATIONS: 'PORTFOLIO_CARDS_OPERATIONS',
  PORTFOLIO_SAVE_CARD: 'PORTFOLIO_SAVE_CARD',
  PORTFOLIO_ADD_PAYMENT_METHOD: 'PORTFOLIO_ADD_PAYMENT_METHOD',
  PORTFOLIO_ADD_CARD: 'PORTFOLIO_ADD_CARD',

  // Documents
  DOCUMENTS_HOME: 'DOCUMENTS_HOME',

  // Preferences
  PREFERENCES_HOME: 'PREFERENCES_HOME',

  // Main
  MAIN: 'MAIN',
  MAIN_MESSAGES: 'MAIN_MESSAGES',
  MAIN_PROFILE: 'MAIN_PROFILE'
}

export default ROUTES
