#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get current unstaged files
unstagedFiles=`git diff --name-only --diff-filter=ACM | grep -E '\.(ts|tsx)$' | sed 's| |\\ |g'`
unstagedCount=`echo "$unstagedFiles" | wc -l | sed 's/ //g'`
echo "Current modified files ($unstagedCount):"
echo "$unstagedFiles"

# Compile the project
echo "🔨 compiling..."
pnpm nx affected --target=tsc-noemit

# Run lintier
echo "🧹 running linter..."  
pnpm nx affected --target=lint --fix --cache
# Run prettifier
echo "🧼 running formatter..."
pnpm prettify

# If we have any modified files don't push
if [ -n "$(git status --porcelain)" ]; then
  # Collect all modified files
  updatedUnstagedFiles=`git diff --name-only --diff-filter=ACM | grep -E '\.(ts|tsx)$' | sed 's| |\\ |g'`
  updatedStagedCount=`echo "$updatedUnstagedFiles" | wc -l | sed 's/ //g'`
  echo "Modified files after linting and formatting ($updatedStagedCount):"
  echo "$updatedUnstagedFiles"

  # Did linter and formatter find some issues?
  newStageFilesCount=$((updatedStagedCount-unstagedCount))  
  if [ "$newStageFilesCount" -gt 0 ]; then
    echo "❌ Some files were not well formed: $newStageFilesCount"
    exit 1
  else
    echo "✅ All files are clean!"
  fi
fi

echo "🚀 pushing..."
echo "✨ Done."