#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get current unstaged files
unstagedFiles=`git diff --name-only --diff-filter=ACM | grep -E '\.(ts|tsx)$' | sed 's| |\\ |g'`
unstagedCount=`echo "$unstagedFiles" | wc -l | sed 's/ //g'`
echo "Current modified files ($unstagedCount):"
echo "$unstagedFiles"

# Compile the project
echo "🔨 compiling..."
yarn tsc:noemit

# Determine the base branch for comparison
BRANCH=$(git rev-parse --abbrev-ref HEAD)
REMOTE_REF="refs/remotes/origin/$BRANCH"
if git show-ref --verify --quiet "$REMOTE_REF"; then
  BASE="origin/$BRANCH"
else
  BASE="origin/master"
fi

ESLINT_FILES=$(git diff -z --name-only --diff-filter=ACMRT \
  "$BASE"...HEAD -- '*.ts' '*.tsx')
if [ -n "$ESLINT_FILES" ]; then
  echo "Running ESLint on changed files..."
  printf "%s" "$ESLINT_FILES" | xargs -0 npx eslint \
    -c .eslintrc.js --ext .ts,.tsx --cache --fix
fi

PRETTIER_FILES=$(git diff -z --name-only --diff-filter=ACMRT \
  "$BASE"...HEAD -- '*.ts' '*.tsx' '*.json')
if [ -n "$PRETTIER_FILES" ]; then
  echo "Running Prettier on changed files..."
  printf "%s" "$PRETTIER_FILES" | xargs -0 npx prettier --write
fi

# If we have any modified files don't push
if [ -n "$(git status --porcelain)" ]; then
  # Collect all modified files
  updatedUnstagedFiles=`git diff --name-only --diff-filter=ACM | grep -E '\.(ts|tsx)$' | sed 's| |\\ |g'`
  updatedStagedCount=`echo "$updatedUnstagedFiles" | wc -l | sed 's/ //g'`
  echo "Modified files after linting and prettifying ($updatedStagedCount):"
  echo "$updatedUnstagedFiles"

  # Did linter and prettier found some issues?
  newStageFilesCount=$((updatedStagedCount-unstagedCount))  
  if [ "$newStageFilesCount" -gt 0 ]; then
    echo "❌ Some files were not well formed: $newStageFilesCount"
    exit 1
  else
    echo "✅ All files are clean!"
  fi
fi

echo "🚀 pushing..."
echo "✨ Done."