# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.5"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build the App in debug mode"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "Debug",
      flags: "-x bundleReleaseJsAndAssets --no-daemon"
    )
  end

  desc "Build the App in release mode"
  lane :build_release do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    gradle(
      task: "assemble",
      build_type: "Release",
      flags: "-x bundleReleaseJsAndAssets --no-daemon"
    )
  end

  desc "Build the App in release mode and deploy a new alpha version to the Google Play Store"
  lane :alpha do
    build_release

    # Generate the changelog from the last commit message
    changelog_from_git_commits(
      commits_count: 1
    )

    upload_to_play_store(
      track: "alpha",
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
