import WALLET_ONBOARDING_SATISPAY_ROUTES from "./routes";

export type PaymentMethodOnboardingSatispayParamsList = {
  [WALLET_ONBOARDING_SATISPAY_ROUTES.START]: undefined;
  [WALLET_ONBOARDING_SATISPAY_ROUTES.SEARCH_AVAILABLE_USER_SATISPAY]: undefined;
  [WALLET_ONBOARDING_SATISPAY_ROUTES.SUGGEST_BPD_ACTIVATION]: undefined;
};
