const WALLET_ONBOARDING_SATISPAY_ROUTES = {
  MAIN: "WALLET_ONBOARDING_SATISPAY_MAIN",

  START: "WALLET_ONBOARDING_SATISPAY_START",
  SEARCH_AVAILABLE_USER_SATISPAY:
    "WALLET_ONBOARDING_SATISPAY_SEARCH_AVAILABLE_USER_SATISPAY",

  SUGGEST_BPD_ACTIVATION: "WALLET_ONBOARDING_SATISPAY_SUGGEST_BPD_ACTIVATION",
  ACTIVATE_BPD_NEW_SATISPAY: "WALLET_ONBOARDING_SATISPAY_ACTIVATE_BPD_NEW"
} as const;

export default WALLET_ONBOARDING_SATISPAY_ROUTES;
