name: Actions to setup environment for all workflows
description: "This action collects the steps to setup any job"
inputs:
  generate-api:
    description: "Whether to generate API clients and upload the artifact"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-pnpm
    - name: Cache Nx
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: .nx
        key: ${{ runner.os }}-nx-cache-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-nx-cache-${{ github.head_ref || github.ref_name }}-
          ${{ runner.os }}-nx-cache-
    - id: generate-api-client
      if: inputs.generate-api == 'true'
      run: pnpm nx run main-app:generate
      shell: bash
    - id: upload-clients-artifact
      if: inputs.generate-api == 'true'
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: api-client
        path: apps/main-app/definitions/
