name: Actions to setup environment for all workflows
description: "This action collects the steps to setup any job"
runs:
  using: "composite"
  steps:
    - id: enable-corepack
      shell: bash
      run: corepack enable
    - id: setup-node
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version-file: ".node-version"
    - id: yarn-cache
      uses: actions/cache@b7a00a3203cfa62623760990f5171f9b4a2ab1a7 # v4.0.0
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
    - id: generate-api-client
      run: yarn generate
      shell: bash
    - id: upload-locales-artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
      with:
        name: locales
        path: locales/
    - id: upload-clients-artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
      with:
        name: api-client
        path: definitions/
