name: Actions to setup environment for all workflows
description: "This action collects the steps to setup any job"
runs:
  using: "composite"
  steps:    
    - id: setup-node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: ".node-version"    
    - name: Enable Corepack and prepare pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare --activate
    - id: yarn-cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        cache: true
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - id: generate-api-client
      run: pnpm generate
      shell: bash
    - id: upload-clients-artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: api-client
        path: definitions/
