name: Actions to setup environment for all workflows
description: "This action collects the steps to setup any job"
runs:
  using: "composite"
  steps:    
    - id: setup-node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".node-version"    
    - name: Checkout
      uuses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v.4.2.0
      name: Install pnpm
      with:
        version: 10
        cache: true
    - name: Install dependencies
      run: pnpm install
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - id: generate-api-client
      run: pnpm generate
      shell: bash
    - id: upload-locales-artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
      with:
        name: locales
        path: locales/
    - id: upload-clients-artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
      with:
        name: api-client
        path: definitions/
