name: Actions to setup environment for all workflows
description: "This action collects the steps to setup any job"
runs:
  using: "composite"
  steps:    
    - id: setup-node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".node-version"    
    - name: Read yarn version from packageManager version
      id: package-manager
      shell: bash
      run: |
        echo "YARN_VERSION=$(node -p "require('./package.json').packageManager")" >> $GITHUB_OUTPUT    
    - name: Prepare and activate the exact Yarn version
      shell: bash
      run: corepack prepare ${{ steps.package-manager.outputs.YARN_VERSION }} --activate
    - id: yarn-cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
    - id: generate-api-client
      run: yarn generate
      shell: bash
    - id: upload-locales-artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
      with:
        name: locales
        path: locales/
    - id: upload-clients-artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
      with:
        name: api-client
        path: definitions/
