export const PaymentsMethodDetailsRoutes = {
  PAYMENT_METHOD_DETAILS_NAVIGATOR: "PAYMENT_METHOD_DETAILS_NAVIGATOR",
  PAYMENT_METHOD_DETAILS_SCREEN: "PAYMENT_METHOD_DETAILS_SCREEN",
  IDPAY_INITIATIVE_DETAILS_LIST: "IDPAY_INITIATIVE_DETAILS_LIST"
} as const;
