/**
 * Main app entrypoint
 */
// Shim file generated by rn-nodeify
import "./shim";
import "react-native-get-random-values";
import "react-native-quick-base64";
import { AlertStatic as Alert, AppRegistry } from "react-native";
import DeviceInfo from "react-native-device-info";
import {
  setJSExceptionHandler,
  setNativeExceptionHandler
} from "react-native-exception-handler";

import "./ts/i18n";
import { isMixpanelInstanceInitialized, mixpanelTrack } from "./ts/mixpanel";
import { name as appName } from "./app.json";
import { initializePushNotifications } from "./ts/features/pushNotifications/utils/configurePushNotification";

// Registers the TaskManager.defineTask handler required by Expo headless runs.
import "./ts/features/itwallet/statusList/tasks";

void initializePushNotifications();

const errorHandler = (e, isFatal) => {
  if (isFatal) {
    if (isMixpanelInstanceInitialized()) {
      mixpanelTrack("APPLICATION_ERROR", {
        TYPE: "js",
        ERROR: JSON.stringify(e),
        APP_VERSION: DeviceInfo.getReadableVersion()
      });
    }
    Alert.alert(
      "Unexpected error occurred",
      `
        Error: ${isFatal ? "Fatal:" : ""} ${e.name} ${e.message}
        You will need to restart the app.
        `
    );
  } else {
    // eslint-disable-next-line no-console
    console.log(e); // So that we can see it in the ADB logs in case of Android if needed
  }
};

setJSExceptionHandler(errorHandler);
setNativeExceptionHandler(exceptionString => {
  if (isMixpanelInstanceInitialized()) {
    mixpanelTrack("APPLICATION_ERROR", {
      TYPE: "native",
      ERROR: exceptionString,
      APP_VERSION: DeviceInfo.getReadableVersion()
    });
  }
});

/**
 * Lazily resolves the React root component for foreground app launches.
 *
 * Expo background tasks also evaluate this entrypoint in a headless JS runtime.
 * Only the global TaskManager.defineTask registration is safe in that path:
 * importing App eagerly would create the Redux store, start sagas and rehydrate
 * persisted state, which may read secure storage while the app is backgrounded.
 */
AppRegistry.registerComponent(appName, () => require("./ts/App").default);
