/**
 * Main app entrypoint
 */
// Shim file generated by rn-nodeify
import "./shim";
import "react-native-get-random-values";
import "react-native-quick-base64";
import React, { useEffect, useState } from "react";
import { AppRegistry, AppState } from "react-native";

import { name as appName } from "./app.json";

// Registers the TaskManager.defineTask handler required by Expo headless runs.
import "./ts/features/itwallet/statusList/tasks";

let AppComponent;

const isForegroundAppState = appState =>
  appState === "active" || appState === "inactive";

const loadForegroundApp = () => {
  if (AppComponent) {
    return AppComponent;
  }

  require("./ts/i18n");
  const { AlertStatic: Alert } = require("react-native");
  const DeviceInfo = require("react-native-device-info").default;
  const {
    setJSExceptionHandler,
    setNativeExceptionHandler
  } = require("react-native-exception-handler");
  const {
    isMixpanelInstanceInitialized,
    mixpanelTrack
  } = require("./ts/mixpanel");
  const {
    initializePushNotifications
  } = require("./ts/features/pushNotifications/utils/configurePushNotification");

  void initializePushNotifications();

  const errorHandler = (e, isFatal) => {
    if (isFatal) {
      if (isMixpanelInstanceInitialized()) {
        mixpanelTrack("APPLICATION_ERROR", {
          TYPE: "js",
          ERROR: JSON.stringify(e),
          APP_VERSION: DeviceInfo.getReadableVersion()
        });
      }
      Alert.alert(
        "Unexpected error occurred",
        `
        Error: ${isFatal ? "Fatal:" : ""} ${e.name} ${e.message}
        You will need to restart the app.
        `
      );
    } else {
      // eslint-disable-next-line no-console
      console.log(e); // So that we can see it in the ADB logs in case of Android if needed
    }
  };

  setJSExceptionHandler(errorHandler);
  setNativeExceptionHandler(exceptionString => {
    if (isMixpanelInstanceInitialized()) {
      mixpanelTrack("APPLICATION_ERROR", {
        TYPE: "native",
        ERROR: exceptionString,
        APP_VERSION: DeviceInfo.getReadableVersion()
      });
    }
  });

  AppComponent = require("./ts/App").default;
  return AppComponent;
};

/**
 * Defers the normal application bootstrap during an iOS background launch.
 *
 * ponytail: the shared JS bundle remains; use a native entrypoint only if
 * strict task isolation becomes necessary.
 */
const ForegroundApp = () => {
  const [RootComponent, setRootComponent] = useState(() =>
    isForegroundAppState(AppState.currentState)
      ? loadForegroundApp()
      : undefined
  );

  useEffect(() => {
    if (RootComponent) {
      return undefined;
    }

    const loadAppIfForeground = nextAppState => {
      if (isForegroundAppState(nextAppState)) {
        setRootComponent(() => loadForegroundApp());
      }
    };
    const subscription = AppState.addEventListener(
      "change",
      loadAppIfForeground
    );
    loadAppIfForeground(AppState.currentState);

    return () => subscription.remove();
  }, [RootComponent]);

  return RootComponent ? React.createElement(RootComponent) : null;
};

AppRegistry.registerComponent(appName, () =>
  isForegroundAppState(AppState.currentState)
    ? loadForegroundApp()
    : ForegroundApp
);
