name: Publish app build (nightly)
on:
  schedule:
    - cron: '59 21 * * *'
concurrency:
  group: nightly-release-master
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  detect-changes:
    name: Detect changes since last tag
    runs-on: ubuntu-24.04
    outputs:
      has_changes: ${{ steps.detect.outputs.HAS_CHANGES }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Get changes since last tag
        id: detect
        shell: bash
        run: |
          set -euo pipefail

          BASE_REF="origin/${BRANCH_NAME}"
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          echo "Last tag: ${LAST_TAG}"

          if [ -z "${LAST_TAG}" ]; then
            RANGE="${BASE_REF}"
          else
            RANGE="${LAST_TAG}..${BASE_REF}"
          fi

          echo "Range for commits: ${RANGE}"

          # Count commits count since last tag, excluding merges and commits by bots
          COMMITS_COUNT=$(git log --no-merges --pretty=format:'%H%x09%ae%x09%an' ${RANGE} \
            | grep -Ev 'github-actions\[bot\]|actions@github.com' \
            | wc -l | tr -d ' ')

          echo "Number of commits since last tag: ${COMMITS_COUNT}"

          if [ "${COMMITS_COUNT}" -gt 0 ]; then
            echo "HAS_CHANGES=true" >> "$GITHUB_OUTPUT"
          else
            echo "HAS_CHANGES=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          BRANCH_NAME: ${{ github.ref_name }}
  run-static-checks:
    name: Run static checks
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/static-checks.yaml
  bump-app-version:
    name: Bump app version
    needs: [detect-changes, run-static-checks]
    uses: ./.github/workflows/bump-app-version.yml
    secrets: inherit
    with:
      release-type: release-rc
  release-android:
    name: Publish Android build to Play Store for internal testers
    needs: bump-app-version
    uses: ./.github/workflows/release-android.yml
    secrets: inherit
    with:
      ref: ${{ needs.bump-app-version.outputs.currentAppVersion }}
      environment: prod
      fastlane-build-lane: alpha
      fastlane-download-lane: download_apk
      universal-apk-filename: io-app-universal.apk
      bundle-output-path: apps/main-app/android/app/build/outputs/bundle/productionRelease/app-production-release.aab
      bundle-artifact-name: app-release.aab
      release-aab-label: android-app-release.aab
  release-ios:
    name: Publish iOS build to App Store for internal testers
    needs: bump-app-version
    uses: ./.github/workflows/release-ios.yml
    secrets: inherit
    with:
      ref: ${{ needs.bump-app-version.outputs.currentAppVersion }}
      environment: prod
      fastlane-lane: beta_testflight
      release-ipa-label: IO-iOS.ipa
