name: Promote latest build to beta
on: workflow_dispatch
jobs:
  distribute-android:
    name: Distribute Android build to closed testing track
    environment: prod
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: setup-ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          bundler-cache: true
          working-directory: apps/main-app
      - id: build-release-android
        run: |
          cd apps/main-app
          ./scripts/android-release.sh ./android/app
          cd android
          bundle exec fastlane promote_internal_to_alpha
        shell: bash
        env:
          ENCODED_IOAPP_JSON_KEY_FILE: ${{secrets.ENCODED_IOAPP_JSON_KEY_FILE}}
  distribute-ios:
    name: Distribute iOS build to TestFlight external testers
    environment: prod
    runs-on: macos-26-xlarge
    steps:
      - id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: setup-ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          bundler-cache: true
          working-directory: apps/main-app
      - id: prepare-ios-build
        run: |
          cd apps/main-app
          ./scripts/ios-release-build.sh
        env:
          APP_STORE_API_KEY_ID: ${{secrets.APP_STORE_API_KEY_ID}}
          APP_STORE_API_PRIVATE_KEY: ${{secrets.APP_STORE_API_PRIVATE_KEY}}
      - id: distribute-app-testflight
        run: |
          cd apps/main-app/ios
          bundle exec fastlane distribute_beta_testflight
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          APP_STORE_API_KEY_ID: ${{secrets.APP_STORE_API_KEY_ID}}
          APP_STORE_API_PRIVATE_KEY: ${{secrets.APP_STORE_API_PRIVATE_KEY}}
          APP_STORE_API_KEY_ISSUER_ID: ${{secrets.APP_STORE_API_KEY_ISSUER_ID}}
  notify-new-version:
    name: Send notification about new beta version on Slack
    environment: dev
    runs-on: ubuntu-24.04
    needs:
        - distribute-android
        - distribute-ios
    steps:
      - id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: get-app-version
        run: |
          cd apps/main-app
          APP_VERSION=$(node -p -e "require('./package.json').version" | sed 's/-rc//')
          echo "version=$APP_VERSION" >> "$GITHUB_OUTPUT"
      - id: send-notification
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.IO_APP_SLACK_HELPER_BOT_TOKEN }}
          payload: |
            channel: "CQVJ1JES2"
            unfurl_links: false
            text: "È disponibile la nuova versione `${{ steps.get-app-version.outputs.version }}` dell’app :io-app: in test interno.\n<https://github.com/pagopa/io-app/blob/master/apps/main-app/CHANGELOG.md|:memo: Changelog> - <https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/345932988/Release+produzione+beta#Frequenza-rilasci|:calendar: Calendario rilasci> - <https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/22020162/Beta+interna|:test_tube: Come partecipo alla beta interna?> - <https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/22020162/Beta+interna#%F0%9F%90%9E-Come-segnalo-un-bug?|:ladybug: Come segnalo un bug?>\ncc <!subteam^S02GBHCR486>"
