# This workflow can be triggered manually to release a new version of the app.
# It supports bumping the app version for major, minor, patch, and build releases.
# It's published to the Play Store internal track and TestFlight for internal testers.
name: Publish app version
on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        description: Version to bump
        required: true
        type: choice
        default: minor
        options:
          - major
          - minor
          - patch
          - build
jobs:
  run-static-checks:
    uses: ./.github/workflows/static-checks.yaml
  bump-app-version:
    name: Bump app version
    needs: run-static-checks
    uses: ./.github/workflows/bump-app-version.yml
    secrets: inherit
    with:
      # releaseLevel is restricted to major/minor/patch/build by the workflow_dispatch choice input
      release-type: ${{ github.event.inputs.releaseLevel == 'major' && 'start-breaking-cycle' || github.event.inputs.releaseLevel == 'minor' && 'start-release-cycle' || github.event.inputs.releaseLevel == 'patch' && 'start-fix-cycle' || github.event.inputs.releaseLevel == 'build' && 'release-rc' }}
  release-android:
    name: Release Android app on Play Store
    needs: bump-app-version
    uses: ./.github/workflows/release-android.yml
    secrets: inherit
    with:
      ref: ${{ needs.bump-app-version.outputs.currentAppVersion }}
      environment: prod
      fastlane-build-lane: alpha
      fastlane-download-lane: download_apk
      universal-apk-filename: io-app-universal.apk
      bundle-output-path: apps/main-app/android/app/build/outputs/bundle/productionRelease/app-production-release.aab
      bundle-artifact-name: app-release.aab
      release-aab-label: android-app-release.aab
  release-ios:
    name: Release iOS app on App Store
    needs: bump-app-version
    uses: ./.github/workflows/release-ios.yml
    secrets: inherit
    with:
      ref: ${{ needs.bump-app-version.outputs.currentAppVersion }}
      environment: prod
      fastlane-lane: beta_testflight
      release-ipa-label: IO-iOS.ipa
  notify-failure:
    name: Notify failure on Slack
    runs-on: ubuntu-24.04
    environment: dev
    if: failure()
    needs:
      - run-static-checks
      - bump-app-version
      - release-android
      - release-ios
    steps:
      - id: send-slack-notification
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        continue-on-error: true
        with:
          method: chat.postMessage
          token: ${{ secrets.IO_APP_SLACK_HELPER_BOT_TOKEN }}
          payload: |
            channel: "C03QJNMTL1E"
            unfurl_links: false
            unfurl_media: false
            text: ":warning: Il workflow `${{ github.workflow }}` è fallito. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Vedi i dettagli>."
