name: Publish app version
on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        description: Version to bump
        required: true
        type: choice
        default: minor
        options: 
        - major
        - minor
        - patch
jobs:
  run-static-checks:
    uses: ./.github/workflows/static-checks.yaml
  bump-app-version:
    name: Bump app version
    needs: run-static-checks
    uses: ./.github/workflows/bump-app-version.yml
    secrets: inherit
    with:
      # releaseLevel is restricted to major/minor/patch by the workflow_dispatch choice input
      release-type: ${{ github.event.inputs.releaseLevel == 'major' && 'start-breaking-cycle' || github.event.inputs.releaseLevel == 'minor' && 'start-release-cycle' || 'start-fix-cycle' }}
  release-android:
    name: Release Android app on Play Store
    needs: bump-app-version
    uses: ./.github/workflows/release-android.yml
    secrets: inherit
    with:
      ref: ${{ needs.bump-app-version.outputs.currentAppVersion }}
      environment: prod
      fastlane-build-lane: alpha
      fastlane-download-lane: download_apk
      universal-apk-filename: io-app-universal.apk
      bundle-output-path: apps/main-app/android/app/build/outputs/bundle/productionRelease/app-production-release.aab
      bundle-artifact-name: app-release.aab
      release-aab-label: android-app-release.aab
  release-ios:
    name: Release iOS app on App Store
    needs: bump-app-version
    uses: ./.github/workflows/release-ios.yml
    secrets: inherit
    with:
      ref: ${{ needs.bump-app-version.outputs.currentAppVersion }}
      environment: prod
      fastlane-lane: beta_testflight
      release-ipa-label: IO-iOS.ipa
