# This workflow is triggered manually and releases a new canary build of the app.
# It's published to the Play Store internal track and TestFlight for internal testers.
name: Publish app canary
on:
  workflow_dispatch:
jobs:
  run-static-checks:
    uses: ./.github/workflows/static-checks.yaml
  prepare-canary-release:
    name: Prepare canary release
    needs: run-static-checks
    runs-on: ubuntu-24.04
    environment: canary
    outputs:
      canaryVersion: ${{ steps.github-release-creation.outputs.CANARY_VERSION }}
    steps:
      - id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-pnpm
      - id: setup-ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          bundler-cache: true
          working-directory: apps/main-app
      - id: resolve-canary-version-code
        run: |
          cd apps/main-app
          echo $ENCODED_IOAPP_JSON_KEY_FILE | base64 --decode > /tmp/json-key.json
          cd android
          bundle exec fastlane current_canary_version_code
        env:
          ENCODED_IOAPP_JSON_KEY_FILE: ${{ secrets.ENCODED_IOAPP_JSON_KEY_FILE }}
      - id: replace-version-with-canary
        run: |
          UPDATED_BUILD_CODE=${{ steps.resolve-canary-version-code.outputs.CURRENT_CANARY_VERSION_CODE }}
          cd apps/main-app
          node scripts/canary/replaceCanaryVersion.js $UPDATED_BUILD_CODE
          mv ios/fastlane/Matchfile ios/fastlane/Matchfile_prod
          mv ios/fastlane/Matchfile_canary ios/fastlane/Matchfile
      - id: bump-version
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .; git commit -m "Replace Matchfile for canary" --no-verify;
          pnpm nx run main-app:release-canary
      - id: push-tags
        run: |
          APP_VERSION=$(node -p -e "require('./apps/main-app/package.json').version")
          git push --no-verify origin tag $APP_VERSION
      - id: github-release-creation
        run: |
          APP_VERSION=$(node -p -e "require('./apps/main-app/package.json').version")
          gh release create $APP_VERSION --generate-notes
          echo "CANARY_VERSION=$APP_VERSION" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-android:
    name: Release Android app on Play Store
    needs: prepare-canary-release
    uses: ./.github/workflows/release-android.yml
    secrets: inherit
    with:
      ref: ${{ needs.prepare-canary-release.outputs.canaryVersion }}
      environment: canary
      fastlane-build-lane: alpha_canary
      fastlane-download-lane: download_canary_apk
      universal-apk-filename: io-app-canary-universal.apk
      bundle-output-path: apps/main-app/android/app/build/outputs/bundle/canaryRelease/app-canary-release.aab
      bundle-artifact-name: app-canary-release.aab
      release-aab-label: android-app-canary-release.aab
  release-ios:
    name: Release iOS app on App Store
    needs: prepare-canary-release
    uses: ./.github/workflows/release-ios.yml
    secrets: inherit
    with:
      ref: ${{ needs.prepare-canary-release.outputs.canaryVersion }}
      environment: canary
      fastlane-lane: canary_testflight
      release-ipa-label: IO-canary-iOS.ipa
  notify-new-version:
    name: Notifiy new version on Slack
    runs-on: ubuntu-24.04
    environment: dev
    needs:
        - prepare-canary-release
        - release-android
        - release-ios
    steps:
      - id: send-slack-notification
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        continue-on-error: true
        with:
          method: chat.postMessage
          token: ${{ secrets.IO_APP_SLACK_HELPER_BOT_TOKEN }}
          payload: |
            channel: "C03QJNMTL1E"
            unfurl_links: false
            unfurl_media: false
            text: "È disponibile la nuova versione `${{ needs.prepare-canary-release.outputs.canaryVersion }}` della canary dell'app."

