name: setup
on:
  workflow_call
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3.0.2
      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - id: install-packages
        run: yarn install --frozen-lockfile
      - id: generate-api-client
        run: yarn generate