on:
  - pull_request
  - merge_group
  - workflow_call
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      shard_matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - id: set-matrix
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Count file changed in the PR to determine the number of shards needed
            FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | wc -l)
            
            # Logic: 1 shard per 20 files changed
            # (e.g., >= 200 files = 10 shards)
            SHARDS=$(( (FILES_CHANGED / 20) + 1 ))
            [ "$SHARDS" -gt 10 ] && SHARDS=10
          else
            # Default for merge_group or master
            SHARDS=10
          fi
          
          JSON=$(node -e "console.log(JSON.stringify(Array.from({length: $SHARDS}, (_, i) => i + 1)))")
          echo "matrix={\"shard\":$JSON}" >> $GITHUB_OUTPUT
  static-checks:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-pr-staticcheck-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - id: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - id: setup
        uses: ./.github/actions/setup-composite
      - id: run-tsc
        run: yarn tsc:noemit
      - id: run-lint
        run: yarn lint
      - id: run-prettier
        run: yarn prettier:check
  unit-test:
    runs-on: ubuntu-latest
    environment: dev
    needs: [static-checks, configure]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.configure.outputs.shard_matrix) }}
    steps:
      - id: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - id: setup-node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".node-version"
      - id: yarn-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - id: install-packages
        run: yarn install --frozen-lockfile
      - id: download-api-client
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: api-client
          path: definitions/
      - id: run-test
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Using --passWithNoTests here cause Jest might not find 
            # related tests for every file changed on every shard
            yarn test:ci \
              --changedSince=origin/${{ github.base_ref }} \
              --shard=${{ matrix.shard }}/${{ strategy.job-total }} \
              --passWithNoTests
          else
            yarn test:ci --shard=${{ matrix.shard }}/${{ strategy.job-total }}
          fi
      - id: codecov-script        
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}