name: Validate publiccode
on: [push, pull_request]

jobs:
  publiccode_validation:
    name: Parse publiccode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: italia/publiccode-parser-action@3244a5a109ae23f76cb379831abbad32927cad8c # v1
      with:
        publiccode: 'publiccode.yml'
