export enum ITW_ISSUANCE_SCREENVIEW_EVENTS {
  ITW_CREDENTIAL_PREVIEW = "ITW_CREDENTIAL_PREVIEW",
  ITW_CREDENTIAL_INTRO = "ITW_CREDENTIAL_INTRO"
}

export enum ITW_ISSUANCE_ACTIONS_EVENTS {
  ITW_ADD_FIRST_CREDENTIAL = "ITW_ADD_FIRST_CREDENTIAL",
  ITW_UX_CONVERSION = "ITW_UX_CONVERSION",

}
