export enum ITW_ISSUANCE_SCREENVIEW_EVENTS {
  ITW_CREDENTIAL_PREVIEW = "ITW_CREDENTIAL_PREVIEW",
  ITW_CREDENTIAL_INTRO = "ITW_CREDENTIAL_INTRO"
}

export enum ITW_ISSUANCE_ACTIONS_EVENTS {
  ITW_ADD_FIRST_CREDENTIAL = "ITW_ADD_FIRST_CREDENTIAL",
  ITW_UX_CONVERSION = "ITW_UX_CONVERSION",
  ITW_CREDENTIAL_START_ISSUING = "ITW_CREDENTIAL_START_ISSUING",
  ITW_ISSUANCE_CREDENTIAL_SCROLL = "ITW_ISSUANCE_CREDENTIAL_SCROLL"
}

export enum ITW_ISSUANCE_ERRORS_EVENTS {
  ITW_ID_NOT_MATCH = "ITW_ID_NOT_MATCH",
  ITW_ID_REQUEST_FAILURE = "ITW_ID_REQUEST_FAILURE",
  ITW_DEVICE_NOT_SUPPORTED = "ITW_DEVICE_NOT_SUPPORTED",
  ITW_ADD_CREDENTIAL_FAILURE = "ITW_ADD_CREDENTIAL_FAILURE",
  ITW_ADD_CREDENTIAL_UNEXPECTED_FAILURE = "ITW_ADD_CREDENTIAL_UNEXPECTED_FAILURE",
  ITW_ADD_CREDENTIAL_NOT_ENTITLED_FAILURE = "ITW_ADD_CREDENTIAL_NOT_ENTITLED_FAILURE",
  ITW_ADD_CREDENTIAL_INVALID_STATUS = "ITW_ADD_CREDENTIAL_INVALID_STATUS",
  ITW_ID_REQUEST_UNEXPECTED_FAILURE = "ITW_ID_REQUEST_UNEXPECTED_FAILURE",
  ITW_CIEID_CIE_NOT_REGISTERED = "ITW_CIEID_CIE_NOT_REGISTERED",
  ITW_ADD_CREDENTIAL_NOT_TRUSTED_ISSUER = "ITW_ADD_CREDENTIAL_NOT_TRUSTED_ISSUER",
  ITW_CREDENTIAL_REISSUING_FAILED = "ITW_CREDENTIAL_REISSUING_FAILED",
  ITW_GET_CHALLENGE_INFO_FAILED = "ITW_GET_CHALLENGE_INFO_FAILED",
  ITW_ID_REQUEST_FEDERATION_FAILED = "ITW_ID_REQUEST_FEDERATION_FAILED"
}

export enum ITW_ISSUANCE_EXIT_EVENTS {
  ITW_USER_EXIT = "ITW_USER_EXIT",
  ITW_BACK_TO_WALLET = "ITW_BACK_TO_WALLET"
}

export enum ITW_ISSUANCE_TECH_EVENTS {
  ITW_ID_REQUEST_SUCCESS = "ITW_ID_REQUEST_SUCCESS"
}
